### ISSUE TITLE
Document URL length-based request method switching for Server Islands v5

### ISSUE THREAD

**Issue by apatel369** [withastro/docs#10125]
### 📚 Subject area/topic

Server Islands

### 📋 Suggested page

https://5-0-0-beta.docs.astro.build/en/guides/server-islands/

### 📋 General description or bullet points (if proposing new content)

See related [thread](https://discord.com/channels/830184174198718474/1312765705208336535) in discord 

In Astro v5, Server Islands requests automatically switch between GET and POST methods based on URL length:

- GET: Used by default for Server Islands requests
- POST: Automatically used when URL length exceeds 2048 characters (Chrome's limit)

This behavior impacts caching possibilities since POST requests are not cached by default.

Should we document this behavior on the Server Islands page?

**Comment by louisescher** [comment]
Hi, thanks for making an issue about this! I'll do a proper write-up the next few days so we can get it into the v5 docs once that's released :)

**Comment by louisescher** [comment]
First draft for a possible section:

## Caching

Generally, it is possible to cache server islands since their data is retrieved via a `GET` request. However, since Astro passes the props as an encrypted string in the query, in cases where the URL becomes larger than 2048 bytes [the request will be ignored by the browser](https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#url-length). In such cases, Astro will send a `POST`  request instead that contains all props in the body. `POST` requests are not cached by all major browsers due to their common use for forms, so this will break any caching logic you have set up. To avoid this issue, try not to pass any big props like objects or arrays to your server islands.


I couldn't find any source on the POST caching, I just know from personal testing that Chrome refuses to cache POST responses and so does Firefox. I have no way to test on Safari unfortunately. 
What's interesting here is that technically, the HTTP spec allows for these requests to be cached just like any other. I think it's just a browser specific issue.

**Comment by sarah11918** [comment]
I'm going to loop in @matthewp to vet this information here! 

(I will help edit into docs style when it's time, but we need confirmation from Matthew that a) this is how it works, b) this is something we want documented about how it works.

**Comment by sarah11918** [comment]
On Talking and Doc'ing we vetted the content of the description above and agree that a short section on Caching server islands makes sense on the server islands guide page, focusing on the potentially unexpected breaking of any caching logic when the request gets too large.
