### ISSUE TITLE
Tailwind CSS v4 Beta

### ISSUE THREAD

**Issue by sakgoyal** [withastro/docs#10156]
### 📋 Explain your issue

Hello,
Is there any current docs on the new v4 beta in tailwind? 
There are breaking changes that the `@astrojs/tailwind` package does not seem to support

**Comment by sarah11918** [comment]
Hi! We have not updated `@astrojs/tailwind` for the beta because we would normally wait for a stable release to update our own integration. So there is not yet any documentation to update because our integration has not updated.

However, [Astro Tips](https://astro-tips.dev/tips/tailwind-v4/) has written some helpful advice on this topic, so we suggest reading that! 🙌
