### ISSUE TITLE
Update to v5 Legacy content collections section

### ISSUE THREAD

**Issue by OliverSpeir** [withastro/docs#10152]
### 📚 Subject area/topic

Update to v5 guide

### 📋 Page(s) affected (or suggested, for new content)

[en/guides/upgrade-to/v5/](https://docs.astro.build/en/guides/upgrade-to/v5/#legacy-v20-content-collections-api)

### 📋 Description of content that is out-of-date or incorrect

https://github.com/withastro/docs/blob/7d726121b0e784a3c62dcb322ab90426307cd2c7/src/content/docs/en/guides/upgrade-to/v5.mdx?plain=1#L150-L151

should be 

```js
    params: { slug: post.slug },
    params: { slug: post.id },
```

also 

https://github.com/withastro/docs/blob/7d726121b0e784a3c62dcb322ab90426307cd2c7/src/content/docs/en/guides/upgrade-to/v5.mdx?plain=1#L132

gives [no-useless-escape](https://eslint.org/docs/latest/rules/no-useless-escape) from eslint

I think this will work the same

```js
loader: glob({ pattern: "**/[^_]*.md", base: "./src/data/blog" }),
```

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

https://github.com/OliverSpeir/astro-starter/blob/8a49d0fbdadd957e2b32b44a2abd6ced1d257135/src/pages/blog/%5Bslug%5D.astro#L8
https://github.com/OliverSpeir/astro-starter/blob/8a49d0fbdadd957e2b32b44a2abd6ced1d257135/src/content.config.ts#L5

https://stackblitz.com/github/oliverspeir/astro-starter

**Comment by OliverSpeir** [comment]
You're right I missed  `src/pages/[id].astro` and didn't realize we no longer suggested using `[slug]` at all

**Comment by sarah11918** [comment]
> But if they had [id].astro they wouldn't have params: { slug: post.slug } they would have params: { id: post.slug },

Right, but the explanation in the text above says `You may also need to update dynamic routing file names to match a changed getStaticPaths() parameter:` So, we're assuming you HAD the `[slug]` param, and are showing updating to `[id]`. It's called out and intentional!

And, it's not like you *can't* use slug as your param, it's only that there *is* no slug property anymore. So in the case of the tutorial, it's not *wrong*: `[...slug]` is the param, so the params key is `slug` while the value is the post's `id` (which is the property each entry has).

```
src/pages/posts/[...slug].astro // [`slug`] parameter

params: { slug: post.id }, props: { post }, // params key = slug; value = id
```

**Comment by ascorbic** [comment]
I think it's right that we don't need the `\`, so the examples can be updated
