### ISSUE TITLE
Add: Explain how to use .yml data files

### ISSUE THREAD

**Issue by swift502** [withastro/docs#1274]
I had to ask this on discord because I couldn't find it in the docs. I think it might help others looking for the same thing, since in my opinion you'd expect it to be much simpler than it is.

## Proposal

Somewhere near the [JSON](https://docs.astro.build/en/guides/imports/#json) section, explain that in order to import .yml files, the user needs to:

1. Install @rollup/plugin-yaml:

```shell
npm install @rollup/plugin-yaml --save-dev
```

2. In astro.config.js import it and add it to the vite plugins array:
```diff
import { defineConfig } from 'astro/config';
+ import yaml from '@rollup/plugin-yaml';

export default defineConfig(
{
+  vite: {
+    plugins: [yaml()]
+  }
});
```
3. Import .yml files as such:
```js
const data = await Astro.glob('data.yml');
```

Please let me know what you think. I can make a PR if this was desirable. Thanks!

**Comment by sarah11918** [comment]
Thanks for this @swift502! Firstly, I'm glad that importing `.yml` files is working for you.  🙌 

Secondly, I'm going to confirm with our Technical Steering Committee that this is the process they want documented. While you certainly can add Vite plugins directly, I think in some cases that's thought of as a bit of an escape hatch solution. So I first want to make sure there's not a different way that engineering is expecting you to do this and/or that this isn't something they want to try to change internally so that a Vite plugin wouldn't be necessary.

But yes, after we have confirmation, then I'd love for you to contrubute a PR! Sit tight! I'll be back...

**Comment by swift502** [comment]
@delucis Oh wow, you're right. `import` does work.

Demo: https://stackblitz.com/edit/github-g5iwb3?file=src/pages/index.astro

The third step should then probably use the import statement.

**Comment by swift502** [comment]
How general should the example be then? Should we mention how/where users should look to find the specific plugin they need for their spcific format?

Or should we just showcase how yml is done and leave it at that?

**Comment by delucis** [comment]
> should we then also mention how/where users should look to find the specific plugin they need for their spcific format?

Something small would be helpful yes! I guess Vite plugins are the other option to look out for?

**Comment by swift502** [comment]
@delucis I'll make a draft PR then. 👍
Let's discuss the wording in the PR.

**Comment by delucis** [comment]
Awesome — thanks so much @swift502!
