### ISSUE TITLE
Vercel deployment docs conflict

### ISSUE THREAD

**Issue by alex-grover** [withastro/docs#1412]
The default Vercel deploy docs state that you don't need any additional configuration to deploy static sites, while the `@astrojs/vercel` docs state that you need a `vercel.json`.

https://docs.astro.build/en/guides/deploy/vercel/#static-site
https://docs.astro.build/en/guides/integrations-guide/vercel/#why-astro-vercel

I'm happy to make a PR, but I'm not sure which docs are correct.

**Comment by sarah11918** [comment]
Thanks for this, @alex-grover! This is a documentation issue, but not the one you're thinking of!

In fact, both docs are correct because the Vercel integration is only for SSR, and is not necessary for deploying static sites. 

Someone added a note for the adapter usage about the `vercel.json` file in the wrong place on that adapter page, and it's misleading right now because it looks like it's related to static site deployment. I have a note to go and change that information's location to be further down the page, where it's clear that it is a note about this SSR adapter's usage. I'm sorry you hit this before I could get that change made!

I'm assuming the original wording I intend to revert to at the top of the page would not be confusing?

> If you’re using Astro as a static site builder — its behavior out of the box — you don’t need an adapter. 
>
> If you wish to [use server-side rendering (SSR)](https://docs.astro.build/en/guides/server-side-rendering/), Astro requires an adapter that matches your deployment runtime.

**Comment by alex-grover** [comment]
thanks for the clarification! your proposed updates make sense to me 👍🏽
