### ISSUE TITLE
Add @astrojs/image integration template to astro.new

### ISSUE THREAD

**Issue by panwauu** [withastro/docs#1424]
In [astro.new](https://astro.new/) there is no integration template for the image integration. As it is an integration of withastro this would make it easier for improvements on the image integration.

**Comment by sarah11918** [comment]
Thanks for this comment! I'm going to make sure @tony-sull sees this, and he can consider whether he thinks an image template is appropriate, or maybe instead adding the image component to some of our existing templates like the blog or basics.

I do know that we probably wouldn't choose to include this integration quite yet, at least not until it reaches v1, as there is still active development and more changes to come. Maintaining a template with this integration would be tricky right now, and we do want to make sure that any template we provide is stable enough to be a good experience for people testing it out!

As this is not a Docs issue, I'm going to close this issue here, but Tony will be on top of promoting the heck out of the integration once we think it's ready for prime time! And, I'm sure that includes making its way into a template on astro.new! 😄
