### ISSUE TITLE
Hydrating SolidJS component throws error on next sibling null

### ISSUE THREAD

**Issue by luke-cbs** [withastro/docs#1425]
Currently using SolidJS components in Astro. When trying to run `client:load` on a component the console throws an error:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')`

This works fine when working with dev however on a build this issue occurs.

**Comment by Yan-Thomas** [comment]
Hello @luke-cbs, for Astro-related issues, please make an issue in the main Astro repo: https://github.com/withastro/astro/issues.
It has a special template for bug reports, that's why I'm asking you to make a new issue instead of transferring this one. This way you can fill out the necessary info and link to a minimal reproduction, which helps a lot!
