### ISSUE TITLE
`@astro/image` should call out usage of content-visibility attribute

### ISSUE THREAD

**Issue by susickypavel** [withastro/docs#1517]
Hi 👋

Today, I've spent a large amount of time debugging an issue about image not rendering when coming to viewport. After checking my code for flaws in animation, I found out that the issue was usage of `content-visibility` property which should alter the default behaviour of image rendering. It should be mentioned in some way that this property is declared by default by Picture/Image.

**Comment by delucis** [comment]
Tagging in @tony-sull for an opinion here so we can discuss what kind of docs this might need.

**Comment by Thesoreon** [comment]
I think it could be batched together in some callout. I'd like to see something like that Image and Picture components are optimized by default by the integration, so attributes like `loading`, `decoding` and attribute `content-visibility` have optimized defaults (but they could lead to weird edge-cases). Since lazy loading images that are in initial viewport is wasteful and it have negative impact on website's FCP/LCP I'd say that such callout could be useful.

**Comment by sarah11918** [comment]
11 days is a long time in Astro Image Integration land!  😅 

I will make sure that I touch base on this with @tony-sull as developments are happening rapidly, and we'll keep this on everyone's radar!

**Comment by delucis** [comment]
Sounds like this is a non-docs issue then, so hope it’s OK if I close this here for now with the intention that it gets resolved upstream.
