### ISSUE TITLE
manual install: tsconfig.json; maybe src/env.d.ts

### ISSUE THREAD

**Issue by mrienstra** [withastro/docs#1558]
https://docs.astro.build/en/guides/typescript/#setup says:
>Astro starter projects include a `tsconfig.json` file in your project. Even if you don't write TypeScript code, this file is important so that tools like Astro and VS Code know how to understand your project. Some features (like npm package imports) aren't fully supported in the editor without a `tsconfig.json` file. If you install Astro manually, be sure to create this file yourself.
(this paragraph was improved very recently, see https://github.com/withastro/docs/pull/1509/files)

Seems like https://docs.astro.build/en/install/manual/ should at least briefly mention `tsconfig.json`, if not outright have a step in which you make it. Imagining it makes sense as a new step 5, before the current step 5 (which would then be "6. Create `astro.config.mjs`", followed by "7. Next Steps").

Ditto for `src/env.d.ts`. Sounds like it's also important to have that (or `"compilerOptions":{"types":["astro/client"]}`). Both of these could be covered in a new step 5, since it boils down to "Create `tsconfig.json` & `src/env.d.ts`, or just the former with `"compilerOptions":{"types":["astro/client"]}`.

Hmm... It would end up repeating a lot of stuff from [guides/typescript/#setup](https://docs.astro.build/en/guides/typescript/#setup), and make the manual install longer, so it's tempting to just say "go read this other thing", but that breaks up the flow ("jump directly to [Step 2: Start Astro](https://docs.astro.build/en/install/auto/#2-start-astro-) to continue").

It could be streamlined in several ways:

1. Don't mention `src/env.d.ts`, and just say that `tsconfig.json` should contain:

```json
{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "types": ["astro/client"]
  }
}
```

2. Don't say anything about the [three tsconfig templates](https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/), just throw in something about checking [guides/typescript/#setup](https://docs.astro.build/en/guides/typescript/#setup) for more info.

Happy to open a PR for this.

**Comment by sarah11918** [comment]
Thanks @mrienstra! We have very recently updated our TypeScript configuration (and advice), and I think you're right, something on the manual install page would be helpful.

My initial thinking is your Option #1 (to say, create this file with this content) could go immediately after our Step 5, where we instruct to do exactly that with the `astro.config.mjs` file. So, it would seem to be entirely consistent to then ask in a Step 6 to manaully create this tsconfig file. And, the option of adding the compilerOptions here instead of having the `env.d.ts` makes sense so that we can keep the steps concise.

While we try to avoid duplicating content when possible, especially here we don't want people to be forced to leave the page as they work through the steps to get a project configured for the first time! We don't have to go into too much detail, but it should be noted that this file should be included whether or not you intend to actually write TypeScript yourself, as some of Astro's features depend on it.

Then, I would also update the project structure tree diagram to include this file.

If you're happy to make a PR, then let's do this one! I would say start with the direction I gave above, and we'll see what it looks like in PR form, then we'll loop others in to fine-tune it!
