### ISSUE TITLE
Document configuring `tsconfig.json` for every integration

### ISSUE THREAD

**Issue by jasikpark** [withastro/docs#1607]
It'd be great if the docs like https://docs.astro.build/en/guides/integrations-guide/react/ also had guides for how to set up the types & keep them up-to-date w/ astro's react so that `npx astro check` and `npx tsc -p ./tsconfig.json` both work great!

For example, we use `@astrojs/react`  and `@astrojs/image` at my job and our tsconfig looks like:

```json
{
  "extends": "astro/tsconfigs/strictest",
  "compilerOptions": {
    "jsx": "react-jsx",
    "types": ["@astrojs/image/client", "@types/react"],
     ... (uninteresting config values omitted)
  }
}
```

I needed to switch to `react-jsx` to get eslint to not yell at me about importing React + needed to add the react types for bare `tsc` to pick up the values

**Comment by jasikpark** [comment]
ah, okay - i guess it depends on which path you choose if you use different client types like in the case of @astrojs/image

**Comment by Princesseuh** [comment]
> ah, okay - i guess it depends on which path you choose if you use different client types like in the case of @astrojs/image

Even then, the main recommendation there is to update `env.d.ts` 😄 https://docs.astro.build/en/guides/integrations-guide/image/#update-envdts

`types` is a weird and misunderstood thing for many TypeScript users, I wish it was more clear that it makes things explicit

**Comment by delucis** [comment]
Couple notes from our triage call:

1. We should maybe update [the Typescript page](https://docs.astro.build/en/guides/typescript/#setup) to more strongly recommend using `env.d.ts` instead of the `types` array in `tsconfig.json`.

2. In the [manual install guide](https://docs.astro.build/en/install/manual/#6-create-tsconfigjson) we should also switch to showing `env.d.ts` and not the `types` array as a best practice.
