### ISSUE TITLE
npm create astro: command not found (WSL)

### ISSUE THREAD

**Issue by agamm** [withastro/docs#1616]
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows WSL2 Ubuntu

### Describe the Bug

I created a new Astro project by: 
`npm create astro@latest`

Then after going into the directory and running `astro add react` I get: 
> astro: command not found

### Link to Minimal Reproducible Example

It's probably an OS error.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello, moving this to the docs repo so our docs team can triage it (and fix it depending on how they see fit)! cc @sarah11918

**Comment by sarah11918** [comment]
Hi @agamm @MoustaphaDev !

The instructions do say to `use your favourite package manager to run this command` and slightly below where your screenshot ends is an example of the specific command to use for each different package manager.

I'm just checking that the documentation below is not clear enough? We do say `astro dev` in the text so that we name "the Astro dev command" as a general concept because different people will be using different package managers. But, we then immediately instruct you to use one of the explicit commands below, shown as a code snippet with the exact line to type in the command line.

Can you let me know what you think would make this clearer to refer to the name of the command to start the dev server while still not being opinionated about which package manager you run it with? Do you take issue with the `astro dev` command being formatted as code, thinking that you should run it? Does it draw your attention more than the actual command to run below?

![Screenshot 2022-09-29 11 38 53](https://user-images.githubusercontent.com/5098874/193062018-5d26cc2a-78cb-4de2-be94-070bc0050937.png)

Here is the shot of the integration documents you describe, where unfortunately because the text comes from a README file, we can't use our fancy tab switching component. I just want to clarify that the docs currently make you think you should run the phrase from the text, the name of the command, rather than the actual executable line below it? Want to make sure I'm understanding the problem so I can investigate!

![Screenshot 2022-09-29 11 42 35](https://user-images.githubusercontent.com/5098874/193062863-474ecadf-6749-41f8-a7da-a87c56e365d9.png)

**Comment by agamm** [comment]
> Hi @agamm @MoustaphaDev !
> 
> The instructions do say to `use your favourite package manager to run this command` and slightly below where your screenshot ends is an example of the specific command to use for each different package manager.
> 
> I'm just checking that the documentation below is not clear enough? We do say `astro dev` in the text so that we name "the Astro dev command" as a general concept because different people will be using different package managers. But, we then immediately instruct you to use one of the explicit commands below, shown as a code snippet with the exact line to type in the command line.
> 
> Can you let me know what you think would make this clearer to refer to the name of the command to start the dev server while still not being opinionated about which package manager you run it with? Do you take issue with the `astro dev` command being formatted as code, thinking that you should run it? Does it draw your attention more than the actual command to run below?
> 
> ![Screenshot 2022-09-29 11 38 53](https://user-images.githubusercontent.com/5098874/193062018-5d26cc2a-78cb-4de2-be94-070bc0050937.png)
> 
> Here is the shot of the integration documents you describe, where unfortunately because the text comes from a README file, we can't use our fancy tab switching component. I just want to clarify that the docs currently make you think you should run the phrase from the text, the name of the command, rather than the actual executable line below it? Want to make sure I'm understanding the problem so I can investigate!
> 
> ![Screenshot 2022-09-29 11 42 35](https://user-images.githubusercontent.com/5098874/193062863-474ecadf-6749-41f8-a7da-a87c56e365d9.png)

A simple fix would be `<package maanger> astro dev` or `npm/yarn/pnpm astro dev`?
