### ISSUE TITLE
Cannot search for "define:vars"

### ISSUE THREAD

**Issue by leoj3n** [withastro/docs#164]
When searching for `define:vars` using the algolia search (top right) it doesn't find this page:

https://docs.astro.build/en/guides/styling/#variables-in-scripts--styles

Or any relevant page to "define:vars". Not sure if this can be fixed?

Also note, the documentation here might be improved to explain the double `{{` syntax...
Something like `{myval}` expands to `{myval: myval}`, and that is within an outer `{` which is a JSX expression.

> The object literal property value shorthand was introduced in ES6 to make the object initialization shorter. It allows us to define an object whose keys have the same names as the variables passed-in as properties, by simply passing the variables like `{myval}` which is interpreted as `{myval: myval}`.

**Comment by zadeviggers** [comment]
I'm pretty sure that's an Algolia limitation. Maybe a sign to move away from Algolia to a custom-built search system?

**Comment by sarah11918** [comment]
Thanks @leoj3n @zadeviggers In fact, I'm not seeing ANY search results for ANY in-code text. 

I came across this:  https://docsearch.algolia.com/docs/docsearch-program/#can-you-index-code-samples  so it might be a configurable (and, I'm guessing, not by default) feature of Algolia, and they do not recommend doing it.

I think this means that we should make sure that words we expect people to search for are at least in regular text somewhere, not in a code sample only! I'll mention this to our docs team so that it's in our collective hive-mind, and part of our strategy going forward as we refresh existing pages and write new ones.

As for the 2nd issue (double `{{` ) I'll take that into consideration when writing! We have to maintain a balance between documenting how *Astro* works, vs documenting ES6, JSX etc. in general (which is not our mandate, and can get overwhelming for readers who just want to know how Astro is working). So, we're trying! This page is currently being refreshed right now and I'll pay special attention to this.  :)
