### ISSUE TITLE
Site style improvement

### ISSUE THREAD

**Issue by zihan-ch** [withastro/docs#1672]
Actually when I first saw the docs of Astro, I felt that it is a little ugly.🤣

Compared to most of the other doc websites, Astro Docs has a lot of differences:

1. Its homepage is separated from its docs(Or its docs are separated from its homepage). This caused that visitors cannot use their own languages at Astro's [homepage](https://astro.build). As well, it's kind of difficult to find the sources about Astro when reading Astro's docs(You need to visit Astro's homepage to look for them).
2. This will also cause that contributors cannot focus on both the homepage and the docs. They have a completely different style! When you visit Astro's docs from its homepage, it seems to change a project...
3. Combine the homepage and the docs may make Astro seem to be more active.(Imagine if there are many community links on its docs: It will be attracting me to visit them when reading docs.)
4. The style of the docs looks really weird! It looks just like websites in 2000...

Compared with [Docusaurus](https://docusaurus.io/), if you have never seen Astro's and Docusaurus's Doc, which will you choose???

Or IDK if this is the style of Astro? Or to show the speed?

<img width="1420" alt="Screenshot 2022-10-02 at 10 21 14 AM" src="https://user-images.githubusercontent.com/110709026/193435080-06ab45d3-1992-4382-aa4f-6344d448d0b2.png">

<img width="1424" alt="Screenshot 2022-10-02 at 10 22 25 AM" src="https://user-images.githubusercontent.com/110709026/193435105-b7b3f0d2-f6a7-4e2f-a512-f48a82190e5e.png">

I believe that it is time to improve it.

**Comment by sarah11918** [comment]
We have several short- and long-term goals for our docs! We are choosing to focus our current resources on the areas of most importance to us right now that we believe will help the most people as they learn and work with Astro. Specifically, we are most concerned with translations to reach as many people as possible and improving the organization of our content so that our important information is available, and easy to find.
