### ISSUE TITLE
Need a custom 404 page

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#175]
Especially now that we removed the "Quick Start" page and replaced all instructions with the Installation page, we should really have a custom 404 page.

This could be a fun thing for someone to build and a great project for a new contributor!

**Comment by sarah11918** [comment]
For now, it's very likely /en/quick-start that is a broken link, so this page should probably include an easy path to the Installation Guide

**Comment by sarah11918** [comment]
Heads up, maybe not such a good first issue quite yet!  We're also tracking a bug in Astro for 404 pages: https://github.com/withastro/astro/issues/2661

**Comment by delucis** [comment]
Just a note to say that there is currently [a basic 404 page](https://github.com/withastro/docs/blob/cabf1a1a128640a680f0b9dc167efd92d27aec33/src/pages/404.astro). Due to [a regression in static builds](https://discord.com/channels/830184174198718474/830184175176122389/948307773819584622) it’s built to `404/index.html` and not currently picked up by Netlify. The German translation also includes [a translated 404](https://github.com/withastro/docs/blob/main/src/pages/de/404.astro).

One more thing we could add to handle localised 404 pages would be a redirect in `netlify.toml`:

```toml
[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404
```

That would mean any language that included a 404 page could serve its own version. (Might look like this redirects _everything_ to 404, but [Netlify is clever](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling).)

**Comment by sarah11918** [comment]
Thanks, @delucis , so less of a "needs a 404 page" and more of a "needs the bug to be fixed."  :)

I'm going to close this, but will add a new issue to add a Netlify redirect. We might not be able to test this until 404s are working again, but that absolutely sounds like a good feature to have!
