### ISSUE TITLE
Why Markdown?

### ISSUE THREAD

**Issue by frantchessico** [withastro/docs#2164]
Why Markdown? Why not HTML itself? I think the following, using Markdown as a template system only increases the process of Astro, because once the template is done with Markdown it will have to be transpiled into HTML again during build or even during development. So using HTML as a template system would improve something.

**Comment by delucis** [comment]
Hi @frantchessico! Markdown is a format for easily writing text for the web — it provides simple syntax for common HTML tags to make it quicker to write rich text.

For example with Markdown you write

```md
# Notes

Plans for the day:

- Try writing a _cool_ page using Markdown!
- Write a post for [my blog](/blog)
```

To do the same with HTML, you’d need to write

```html
<h1>Notes</h1>

<p>Plans for the day:</p>

<ul>
  <li>Try writing a <em>cool</em> page using HTML!</li>
  <li>Write a post for <a href="/blog">my blog</a></li>
</ul>
```

A lot of people find it simpler to write using Markdown rather than authoring HTML directly.

However, Astro does support several [file types for authoring your content](https://docs.astro.build/en/core-concepts/astro-pages/) including `.md`, `.mdx`, `.html` and `.astro`.

I’ll close this as these issues are for tracking improvements to the Astro docs but thanks for checking in 🙌
