### ISSUE TITLE
Improve Image-Docs / `@astrojs/image` vs. `RafidMuhymin/astro-imagetools` / Page on Comparison with Gatsby

### ISSUE THREAD

**Issue by tordans** [withastro/docs#2236]
I am trying to get into the Astro eco system. Migrating my Gatsby project is astonishingly hard…

One thing, I struggle with, is understanding how to handle Images in Astro. I get the weirdest error messages (more below).

Those things would help me / have helped me:

- On the Gatsby comparison, you reference the community `astro-imagetools`. But you don't mention the `@astrojs/image`. I assume that is just out of date and the current recommendation would be to use `@astrojs/image`? — An update to this section would be perfect.
- On the [`@astrojs/image` page](https://docs.astro.build/de/guides/integrations-guide/image/) there is no mention of `astro-imagetools`. Is `@astrojs/image` already more stable than the community tool? Which should I pick today?
- It would also be ideal, to learn how the two solutions are different, which would be the same as https://github.com/RafidMuhymin/astro-imagetools/issues/116 but from astrojs's side.
- I had a hard time debugging, that I cannot use the `@astrojs/images` components in my react components. This is what I mention at https://github.com/withastro/astro/issues/5673; it would be perfect, if the docs where more clear on this.
- I also wonder: How _do_ I handle images (in a "Gatsby way") in my React components? 
  - Does @astrojs/image have something like  `astro-imagetools` which [apparently auto-optimizes images](https://astro-imagetools-docs.vercel.app/en/usage) referenced in a react component? 
  - Or should I use some [named slot](https://docs.astro.build/en/core-concepts/astro-components/#named-slots) approach to use the astro components in my react component? (Did not understand that fully, yet…)

**Comment by sarah11918** [comment]
Hi @tordans! Thanks for this, and let me address what I can for docs here:

First of all, we have a draft PR for a full "migrate your site to Gatsby" guide that you may find interesting, and are welcome to evaluate and provide PR reviews on!  https://github.com/withastro/docs/pull/2211

Second of all, the Gatsby comparison you mention is in fact on a very old, unmaintained page (there's a notice at the top, and it's been removed from our sidebar navigation) so yes, your observations are correct: at the time of that page's writing, there was no official Image integration and the community plugin (not maintained by Astro) was the only image tool that existed. While that plugin is still maintained and is still an excellent image solution, it is listed in our integrations showcase at https://astro.build/integrations/ but we do not document it as it is not a part of core Astro. You'll find its own documentation on its own site. It is also not our place to document usage of a community integration vs our official integration, but if you hop into our Discord, people will answer questions and chat about it there! In fact, the creator of the community plugin is a maintainer of Astro, so it's very collegial (just, not the purvue of docs).

What I do get from your comment is that our docs could do a better job of explaining that any Astro integration (ours, the community plugins) are **only** for your Astro files themselves. They are Astro packages meant to work in `.astro` files.

The reason we don't provide guidance for "how to work in React" is that when you are writing React... you are *writing React* and Astro doesn't have much to do with it at that point. But, you are using React itself, and not Gatsby. So, however you'd do anything, including images, in "React but not Gatsby" is how you'd do it in Astro. Since any more specific documentation would be exceptionally difficult to maintain and keep updated in our own docs, we typically don't document how other frameworks and libraries work whenever possible, and try to stick to the bits that really do intersect with Astro usage. We wouldn't necessarily know when a React package somewhere changes in order to update our docs, 
so we hesitate to provide particular guidance on using more specialized image solutions in your React components. Similarly, since we support several frameworks, we just can't keep current on how Svelte, Vue etc. handle their images. 

Related, regarding working with slots and React and Astro components together, the same advice holds: a React component is pure React, and is governed by their usage patterns and rules. You cannot write an Astro component inside a React component file. The solution we do offer when you want an Astro child to a React component is described here: https://docs.astro.build/en/core-concepts/framework-components/#can-i-use-astro-components-inside-my-framework-components  Since only an Astro component can contain components from a variety of different frameworks, you can structure your design to make use of `.astro` files in order to achieve this.

So, I'm going to close this issue, since I can see some of your specific concerns are being addressed elsewhere and I will review our current Image documentation for clarity.

I also really do invite you to read, critique, and comment on the draft Migration from Gatsby guide we're working on! We are trying to provide some helpful guidance, and welcome feedback!

**Comment by tordans** [comment]
@sarah11918 thanks for taking the time to go into details with your answer!

I have a few thoughts that you might find interesting:

> First of all, we have a draft PR for a full "migrate your site to Gatsby" guide that you may find interesting, and are welcome to evaluate and provide PR reviews on! https://github.com/withastro/docs/pull/2211

Thanks, will have a look.

> Second of all, the Gatsby comparison you mention is in fact on a very old, unmaintained page (there's a notice at the top, and it's been removed from our sidebar navigation)

Here is a workflow that basically hides the notice (which I did not see).

1. Go to https://docs.astro.build/en/getting-started/
2. cmd+k open Search, type Gatsby
3. Click first link, find it not useful …
2. cmd+k open Search, type Gatsby again
3. Click link "Gatsby vs. Astro"
4. => You get scrolled to https://docs.astro.build/en/comparing-astro-vs-other-tools/#gatsby-vs-astro directly. You never see the deprecation notice.

My recommendation: Either remove the content completely. Or add a deprecation notice below each headline, since your search will treat each headline as a separate page, basically.

> You'll find its own documentation on its own site. 

I see you point. Another way of looking at is could be: This community plugin is probably the dominant way to handle images. So it is in the interest of your official solution to migrate users. The "Upgrade from community to official image plugin"-Guide could and should be something that is handled by the official docs. — Such a guide would naturally include a feature comparison, which was what I was looking for.

A hint at which to use right now (which one is to be considered more stable) would also be very helpful for your users.

> What I do get from your comment is that our docs could do a better job of explaining that any Astro integration (ours, the community plugins) are only for your Astro files themselves. They are Astro packages meant to work in .astro files.

Yes, I understand this now — but I think it needs to be made a lot clearer. Not only in docs, but also in linting and error messages, which is why I created https://github.com/withastro/astro/issues/5673.

This is especially pressing for the Image plugin: I will need to have a solution to use images in React. How would I do this, if the `<Image>` component only works in Astro…

There is another issue with this setup: How do I handle shared components linke `<Link>` or `<Button>`. Those components are likely super simple and only hold a list of Tailwind CSS classes to make all Links/Buttons look the same. Whenever I use more than one framework, I do need a way to share those components.

I think there is a lack of tutorials/best practice right now on how to handle this best.

My understanding now is…
- either use the non-astro-framework (in my case React) for all shared components since those can be used in both, react and astro files
- or duplicate the shared components in one React and one .astro Version.

> …we typically don't document how other frameworks and libraries work whenever possible,…

That sounds reasonable. But to be clear, I am talking about documenting how Astro works in terms of using a shared .astro+.jsx Setup.

> … so we hesitate to provide particular guidance on using more specialized image solutions in your React components…

I was referring to Guidance about using your Astro Image Plugin in an Astro+React Setup. Being able to use React is a core selling point of Astro. If the image solution in Astro only works in .astro files, that is a blocking limitation for our projects.

> … Similarly, since we support several frameworks, we just can't keep current on how Svelte, Vue etc. handle their images.…

I don't think React does handle images in any special way. That is way the image solution is not part of React but Gatsby or Next. Its a framework level feature – so in this sense it is Astros burden.

> The solution we do offer when you want an Astro child to a React component is described here: https://docs.astro.build/en/core-concepts/framework-components/#can-i-use-astro-components-inside-my-framework-components

A feedback on the docs: 
- I have been reading this over and over, and I don't get it. I don't understand the consequence of `slot="name"`. Where does this get picket up again? Where is the <slot name="name" />` part in this example-scenario?
- I thing a good addition to this section would be to explicitly list what is not possible; just to make absolutely what is not possible so users don't look for "the docs that explain the other part of this"…

---

Again, thanks for taking the time with your answer. I hope you finde those thoughts useful as well.
