### ISSUE TITLE
Step-by-step guide for Builder.io integration wanted?

### ISSUE THREAD

**Issue by Return180bpm** [withastro/docs#2304]
[Link to the RELEVANT SECTION IN THE DOCS](https://docs.astro.build/en/guides/cms/builderio/)

---

Hey all!

I've recently built a project with Astro and Builder.io and wanna share my newly found knowledge. The article linked in the docs (_Connecting Builder.io’s Visual CMS to Astro by Yoav Ganbar_) helped a lot, but I could have profited from a more beginner-friendly step-by-step guide. So that's what I'm proposing 😁 

Let me know any thoughts You might have and let's make this awesome!

Cheers,
Tom

**Comment by Return180bpm** [comment]
Thanks for linking the PR. Super helpful!

Started working on this last week. [Have asked the folks at Builder a burning question ](https://forum.builder.io/t/what-are-the-pros-and-cons-of-a-dynamic-preview-url/3167?u=habbeda). Should submit the PR next week. 👍

**Comment by sarah11918** [comment]
Hey @Return180bpm! No pressure, just following up on some older issues tonight!

I'm going to close this as an "issue" since we've already discussed that yes, it would be cool if you want to PR something to the Builder.io page and I don't think this needs to hang over anyone's head.  😅 

If you do get around to making a guide, fantastic! If you end up writing a blog post (first?) and just want to PR a link to that, that's cool too! But let's remove the notion of this being an "issue" now. (But you can reopen if you find you need to!) 🚀
