### ISSUE TITLE
Missing results for query "browserslist"

### ISSUE THREAD

**Issue by andrezero** [withastro/docs#2321]
Hi there, first issue 

I want to add auto prefixing to the built CSS and thought installing `browserslists` since I know PostCSS is operating under the hood.

But the docs have 0 mention of this tool and a cursory search yields some concerning results. 

Is it even possible? Would be great to clarify and add simple instructions

I am going to attempt trial and error installation based on https://github.com/withastro/astro/issues/4092 and https://stackoverflow.com/questions/75035565/postcss-autoprefixer-setup-in-an-astro-project hoping with little confidence actually :-D wish me luck

**Comment by sarah11918** [comment]
@andrezero Making my way through issues, and hoping you had some luck here! It looks like the original bug was closed, with *some* related fixes, but concluding that supporting `browserslist` was not necessary and this was not implemented.

I'll close this related docs issue, since if it's not supported, it wouldn't be in docs. But, if you have reason to open another issue with a finding that you think should be included in docs, then please do so!
