### ISSUE TITLE
build ignores package scripts

### ISSUE THREAD

**Issue by 7flash** [withastro/docs#243]
Here is repository to reproduce error:

https://github.com/7flash/sleek-web-second/blob/master/src/components/SleekApp.jsx

Expected, when I run "npm run build" and serve index.html, it should render the same what renders using "npm run dev"

npm run dev:

![image](https://user-images.githubusercontent.com/4569866/159125007-34aeb216-ef2f-44e2-bcbd-abf1576157b0.png)

npm run build:

![image](https://user-images.githubusercontent.com/4569866/159125017-1b0b6eee-915c-4680-81b5-32f35a288d0e.png)

As seen on screenshot, in second case the component imported from package missing styling and functionality too

**Comment by sarah11918** [comment]
Hi @7flash , thanks for reporting this!

These issues are specifically for our documentation site, not for Astro as a product, though, so I'm afraid you won't get the right people looking at your issue here.

Can you please make an issue at the https://github.com/withastro/astro repository? That's where our engineers will be expecting issues like this. Thank you!  :)
