### ISSUE TITLE
Document how to apply a Vite plugin  just to the client build

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2483]
Matthew describes how to do it here (also copied below):  https://github.com/withastro/astro/issues/5870#issuecomment-1405609124

Where would we see this going in docs?

---------
The code shown here is Astro's internal code; it does not run in the browser. I think the problem is you are using a Vite plugin that is running both to transform the server code and the client code.

If you want to run a Vite plugin just on the client code you'll need to use the integration API to do that, which would work something like this:

import pluginLegacy from '@vitejs/plugin-legacy';
import { defineConfig } from 'astro/config';

```
export default defineConfig({
  integrations: [
    {
      name: 'my-integration',
      hooks: {
        'astro:build:setup': ({ vite, target }) => {
          if(target === 'client') {
            vite.plugins.push(pluginLegacy());
          }
        }
      }
    }
  ]
});
```

**Comment by Jutanium** [comment]
I think this fits really well as one of our new Recipes!

**Comment by axelthat** [comment]
https://github.com/withastro/astro/issues/5870#issuecomment-1407368142

**Comment by sasoria** [comment]
I just used this in order to run a plugin to set react and react-dom as externals and fetch them from esm.sh in a client side rendered Island. It also can help to set other dependencies as externals and apply an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap). I've made a couple of examples here:

* [Import map at build time](https://github.com/sasoria/astro-importmaps-bt/blob/main/astro.config.mjs)
* [Import map at run time](https://github.com/sasoria/astro-importmaps-rt/blob/main/astro.config.mjs)

This failed silently when I tried to use [this recipe](https://docs.astro.build/en/recipes/add-yaml-support/#recipe), possibly because it tries to run the plugin/vite-option for the server as well? The use case for this can be to run import maps, those can also be used to share dependencies across micro-frontends.

* [Example with micro-frontends](https://github.com/sasoria/astro-microfrontends)

Let me know if there is anything you'd like to know if something is unclear.

**Comment by sasoria** [comment]
I also wrote an article about [Micro-frontends and Astro](https://medium.com/p/137340d2c520) 😊

**Comment by delucis** [comment]
Not 100% sure if this example works well in all cases, so will close for now rather than documenting.
