### ISSUE TITLE
"Give us feedback" button hidden on mobile

### ISSUE THREAD

**Issue by Jutanium** [withastro/docs#2497]
Unless you're on the tutorial page, the Feedback Fish button is hidden on small screen sizes. Is this intentional?

**Comment by BryceRussell** [comment]
I also see this behavior, if I am on a tutorial page I can see the feedback button but all other pages I can't

I think this is intentional though because on all pages (expect tutorials) as you scroll down it shows the current heading next to the "On this page" button

**Example**:

<img src="https://user-images.githubusercontent.com/19967622/215642432-1d21f3c2-ad47-43ca-982f-e65afd952e44.png" alt="example" width=250>

Since tutorials are a sequence of pages instead of one large page with lots of headings I think the feedback button was used to fill the empty space

Maybe on mobile the feedback button could be placed at the bottom of the page or at the bottom of the main navigation drawer

Also one minor nit pick, the feedback button on the tutorial pages has blue text when on mobile safari

**Comment by Jutanium** [comment]
Docs redesign will solve this!
