### ISSUE TITLE
[tutorial] CSS/responsiveness

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#2608]
From Feeback Fish:

> `.nav-links` first class is hiding the navigation component by default. that afects the responsive width less than 636px

Anyone care to explore this feedback?

**Comment by Jutanium** [comment]
As far as I can tell, this is desired behavior. Because we're doing mobile-first design, we hide the navigation component by default. Then we have a media query to show it at width 636px.

We add all of these styles [at the same time](https://docs.astro.build/en/tutorial/3-components/3/), but it's possible they left this comment before copying the full styles.
