### ISSUE TITLE
Better docs on linting/format on save

### ISSUE THREAD

**Issue by patheticGeek** [withastro/docs#2629]
### Issue:
When setting up a new astro project, I see a lack of docs on getting prettier/eslint and VS Code working together. I do see the prettier & eslint extention's Readme's linked in the docs, but doing steps on both didn't get me to a working state. And even after getting them working, some additional config is required to set up "Format on save" feature.

For me personally, having good formatting/linting support & editor integration is an important thing when considering using a framework.

### Possible solutions:
Not sure which one(s) should be chosen, but just thinking out loud
- Link to or include a guide in the docs which shows how to set this up properly
- Create astro integrations (community/official) so user's can just do `astro add eslint`
- Include prettier & eslint config in the default template & some instructions to get "format on save" working (this one might need moving the community eslint plugin in astro?)

Link to how I got this working: https://patheticgeek.dev/blog/astro-prettier-eslint-vscode
More than happy to move this to a gist and link to that if needed

**Comment by sarah11918** [comment]
Hi @patheticGeek, thanks for raising this!  :raised_hands:

Admittedly yes, some of your proposed solutions here aren't for docs, but tackle the root of the issue a different way. I'm going to loop @Jutanium in here because we now have a new "recipes" section in docs. This area was specifically intended to allow us to link to community walk-throughs of accomplishing specific tasks so we can get helpful content out to our readers while letting the community share knowledge... without every little thing being trapped behind the docs PR/review process.

Your own article might be a candidate for that, especially because we have decided that we should avoid documenting too much about things that we don't maintain, like community plugins.

You may also wish to approach this from the plugin side, suggesting adding to *their* documentation.

I'll add the "recipe" tag to this for Dan to further explore as a community link there!

**Comment by Jutanium** [comment]
We've added your article to our community recipes list, and we're happy leaving the ESLint and Prettier sections of our guide as-is. We usually don't document external tools and plugins, and the best place to improve the Astro ESLint guide is its own repo.
