### ISSUE TITLE
Add `src/content/` to project structure guide

### ISSUE THREAD

**Issue by delucis** [withastro/docs#2797]
We received this feedback:

>  content directory not listed in the project-structure page of docs.

I thought about a quick PR adding this but it’s not clear cut — so far we’ve leaned towards content collections being “advanced” usage so perhaps not to be included on [the Project Structure page](https://docs.astro.build/en/core-concepts/project-structure/)?

That said, as we add more “special” directories like `src/content/` and soon `src/assets/`, the value of having a place which gives an overview of all of these increases, so maybe we do want to do this?

**Comment by sarah11918** [comment]
Great observation @delucis 

I think as more of our starter projects begin to include these folders, we maybe should consider it. Also, because these folders are "special" and someone who doesn't intend to use content collections could very well make themselves a `src/content/` folder and then experience problems.

We could have a dedicated section on that project structure page for "reserved" folders (the way we currently call out `src/pages/`... even if someone isn't using the features they correspond to, they should be told not to "choose" these folders for themselves, I think!

Let's do it!

**Comment by WintrCodes** [comment]
> Great observation @delucis
> 
> I think as more of our starter projects begin to include these folders, we maybe should consider it. Also, because these folders are "special" and someone who doesn't intend to use content collections could very well make themselves a `src/content/` folder and then experience problems.
> 
> We could have a dedicated section on that project structure page for "reserved" folders (the way we currently call out `src/pages/`... even if someone isn't using the features they correspond to, they should be told not to "choose" these folders for themselves, I think!
> 
> Let's do it!

What other folders are optional? 
I'll add them in to the tree with "(optional)" or similar appended
