### ISSUE TITLE
[ Blog Tutorial ] Improvements

### ISSUE THREAD

**Issue by ampmonteiro** [withastro/docs#2846]
Hi,

First of all, i learn a lot with this tutorial, thanks.

A few things that i think it is essential and is missing in this tutorial:

-  `active link`, how  to set style for current page that was selected in the Navigation
- `pagination`, this is valid  and relevant  beside blogs, like portfolios or docs too. 

I did try implemented a simple pagination by following your [docs](https://docs.astro.build/en/core-concepts/routing/#pagination), you can see my implementation on this tutorial [here](https://github.com/ampmonteiro/astro-tutorial-blog-pagination).

However, pagination is a must in the tutorial as well as it should be implemented in existed templates in `astro.new `  like blog , docs or portfolio.

Thanks

**Comment by sarah11918** [comment]
Hi @ampmonteiro! I'm glad you learned from the tutorial!

We have just created a new section in docs called "Recipes" which is for these kinds of smaller walk-through examples after someone has completed the basics in the tutorial, and we are actively writing more of them! I do think both of your ideas would make great recipes!

One reason we are doing this instead of adding to the basic tutorial is that the tutorial works best when you work through the WHOLE tutorial. That's why it is kept very minimal and to the basics. Some people already think the tutorial is too long, and it's important to us that everyone be able to complete it!

We also are focusing on recipes for additional content because it would be difficult for someone not doing the whole tutorial to benefit from content there like pagination. But, recipes are shorter, focused guided instructions that anyone can add to any existing project, and are easier to find when they exist as their own page in docs. So that is the direction we are taking with ideas like this.

We are currently deciding how to best collect ideas for new recipes from the community, and I think we will be opening a GitHub Discussion for these. We will add these to the list there!
