### ISSUE TITLE
Flash blank page

### ISSUE THREAD

**Issue by jamesli2021** [withastro/docs#2920]
I have notice on Firefox and Safari will get blank white flash when visit Documentation link from any page in astro.built, probably due to slow rendering? It work fine, no flashing on MS Edge.

Sure did notice the rendering performance when testing Docs on my local dev machine (macOS Ventura Macbook M1).

**Comment by jamesli2021** [comment]
In addition, I think iframe could solve the problem with excessive DOM size which seperate into subdocument.

**Comment by delucis** [comment]
Thanks for the report @jamesli2021! I think this is because navigating from astro.build to docs.astro.build is across two separate sites so there can be a small gap in rendering.

We're currently working on a new docs design that will also try a different approach for the huge list of avatars that I think is main cause of the "excessive DOM size" warning in Lighthouse.

I'll keep this report in mind as we work on the new design 🙌

**Comment by jamesli2021** [comment]
@delucis I have discovered:

1) `https://docs.astro.build/` redirect to `https://docs.astro.build/en/getting-started/` will always appear with white blank flash. This could be easy fix.

2) Contains *Contribute* GitHub avatar into <iframe> will reduce exceed DOM size, as source code
