### ISSUE TITLE
RSS recipe missing final implementation step

### ISSUE THREAD

**Issue by UmungoBungo** [withastro/docs#2942]
I recently added RSS feeds to my site, following the [RSS recipe](https://docs.astro.build/en/guides/rss/). It was all good, except for the fact that I was very unfamiliar with RSS feeds... and so I felt like the final step was missing - I have an RSS feed, but now what? 

It would be good to have a section towards the end of the recipe about accessing the feed via the route, and maybe mention the (standard?) practice of adding an RSS icon that could link to that feed?

After some discussion in the Discord channel, I agree that this shouldn't necessarily be written by the Astro team, but ideally would link to some other documentation. [https://aboutfeeds.com/](https://aboutfeeds.com/) is good on the whole, and is mentioned at the start of the recipe, but it too is missing that final step.

**Comment by sarah11918** [comment]
I think this is a great idea! We do like our docs to be user-friendly, but we ideally *don't* document how to do non-Astro stuff.

How anyone can help: Look for a good article on adding something to your website to display your RSS feed, just that final step of the process!

It should assume someone already HAS an RSS feed set up/configured, and it doesn't have to have anything to do with Astro! Something that talks about adding an RSS icon to your page, or a link to "RSS"... something like that.

This could PR could be as simple as adding a line at the end of the recipe something like:

"After visiting your feed in the browser at (appropriate web URL that fits with the recipe instruction) and confirming that you can see data about your posts, you can now [display your feed on your website]() so that readers can subscribe to it in their own feed reader."

**Comment by CBID2** [comment]
> I think this is a great idea! We do like our docs to be user-friendly, but we ideally _don't_ document how to do non-Astro stuff.
> 
> How anyone can help: Look for a good article on adding something to your website to display your RSS feed, just that final step of the process!
> 
> It should assume someone already HAS an RSS feed set up/configured, and it doesn't have to have anything to do with Astro! Something that talks about adding an RSS icon to your page, or a link to "RSS"... something like that.
> 
> This could PR could be as simple as adding a line at the end of the recipe something like:
> 
> "After visiting your feed in the browser at (appropriate web URL that fits with the recipe instruction) and confirming that you can see data about your posts, you can now display your feed on your website so that readers can subscribe to it in their own feed reader."

I'm eager to help! 😄

**Comment by Jothsa** [comment]
There is a dearth of rss feed tutorials that include this final step. [This one](https://medium.com/samsung-internet-dev/add-rss-feeds-to-your-website-to-keep-your-core-readers-engaged-3179dca9c91e) includes it at the very end. If that looks ok, I'd be happy to make a pr.

**Comment by sarah11918** [comment]
@Jothsa That looks great! Make it so! :point_right:
