### ISSUE TITLE
Additions to the Integrations API documentation

### ISSUE THREAD

**Issue by jose8a** [withastro/docs#308]
Potential improvements to the Integrations API documentation:

A lifecycle diagram on the order in which the hooks are run and also under which scenarios they will be utilized? I initially found it confusing trying to figure out what each hook could be used for, and under which scenarios (e.g. during dev, during build, during SSR, or maybe others?). It wasn't until after looking through the Astro codebase where I realized under which scenarios they will run. It seems obvious now from the naming, but maybe it won't to those looking at them for the first time. 

It may also be helpful to have a kind of `lifecycle diagram` for lack of a better term.  This can be similar to these ones in Lit-dev's docs: https://lit.dev/docs/components/lifecycle/#reactive-update-cycle and similar to the one in vue's options API docs. 

Finally, I think I found some missing documentation in a couple of the Integration hooks. I noticed these couple of things: 

1) there is a hook runHookBuildSetup that isn't in the public-facing docs section of the Integrations API
2) the runHookBuildStart takes in a buildConfig option which isn't in the current public-facing docs.

**Comment by sarah11918** [comment]
Hi @jose8a !

I know @bholmesdev recently added some documentation to the page here: https://docs.astro.build/en/reference/integrations-reference/

How did he do?  😅

**Comment by sarah11918** [comment]
Hi @jose8a !

I'm going to close this issue now, since our Integrations API documentation has received some work, with community input helping to refine the PR, since your initial issue was filed. I know there's no life-cycle diagram in particular, but I do know that Discord was given the chance to weigh in on this page, and several people did.

You are welcome to reopen, or file a new issue (or PR!) with any other specific request. But given this page has recently been completely updated, I'll assume that this page is what @bholmesdev and the community are sticking with for now, and I'm going to close this issue at this time.
