### ISSUE TITLE
 it shows while github hosting 

### ISSUE THREAD

**Issue by Shabeebkaruvath** [withastro/docs#3095]
![image](https://user-images.githubusercontent.com/89894784/234285313-1808d71b-ffaa-4940-93a5-154a90c785ae.png)

**Comment by delucis** [comment]
Hi @Shabeebkaruvath, your screenshot appears to be running `react-scripts` which is part of Create React App not Astro. Are you sure this issue is Astro-related?

In any case, this repository is for the Astro documentation website, not for Astro support. If you're stuck, I'd recommend joining our friendly Discord community at https://astro.build/chat where you can ask for help in the `#support` channel.
