### ISSUE TITLE
Improve GitHub deployment docs

### ISSUE THREAD

**Issue by JetLi2K** [withastro/docs#3127]
https://docs.astro.build/en/guides/deploy/github/

In the Note and Cautious section, I was struggling to read what we should not do but it doesn’t explains why. Especially the “base” path issue which doesn’t seem to work with hardcode link such as

<img src=“/test.jpg”>

Does it automarkcay include base path or require to update all relative URL manually?

**Comment by sarah11918** [comment]
Hi there! As it says in the caution, you must update all your relative links to make sure they include the new `base`. So, instead of just using `/about/` you must now use `/base/about/` as your relative links.

We can't always explain why third-party services work the way they do, since we don't fully know or control the way they work. We sometimes can only explain what you need to do for Astro to work. If you need more assistance deploying to GitHub pages, or with Astro, please visit the Astro Discord and ask a support question! People will be happy to answer there!
