### ISSUE TITLE
Listen to nano Store in astro client side

### ISSUE THREAD

**Issue by Ceyar** [withastro/docs#3181]
Hello I am trying to Listen to a nanostore from my astro file but on the client side. 

But I cant. Someone has a working example or similar issue?  Thank you.

**Comment by dreyfus92** [comment]
This might help https://www.youtube.com/watch?v=Sr4VYks1lPY

**Comment by gitVasile** [comment]
Hey @dreyfus92 thank you but this is not helping. I am searching a solution to make the nano store work in my File.astro on the client side.

**Comment by sarah11918** [comment]
Hi @Ceyar! I'm sorry to hear you're having trouble with this. Have you seen our docs recipe for sharing state using Nano Stores? This is I think the only part in our docs where we discuss Nano Stores: https://docs.astro.build/en/core-concepts/sharing-state/

If you need help, then you can post in our Discord in a support thread at https://astro.build/chat . That's where we offer support when you need help. These issues are for issues to fix in our documentation, so the people reading this thread are people working on the docs, not our support squad.

So I'm going to close this thread since it's not a docs issue you're having, but please do ask for help in our Discord!
