### ISSUE TITLE
Link to i18n locale page forced by search engine language

### ISSUE THREAD

**Issue by vincentdorian** [withastro/docs#3199]
### The Problem

When accessing the Astro docs via Google Search, the recommended link to the specific page is influenced by the default language set in the Google Search settings.

In my case, the default language is set to "German". In case of for example using a query "why astro" in Google, the following result is obtained. 

![image](https://user-images.githubusercontent.com/60883844/236682127-95ab39d9-6930-413f-b420-5a980adfadab.png)

Changing the default search language to "English" will result in the following:

![image](https://user-images.githubusercontent.com/60883844/236682072-087b4210-4d3d-4147-838c-694432e95ef7.png)

Of course, once I have navigated to the Astro docs, I will only navigate between pages with the selected locale within the site (English).

While, for people who want to browse the docs in their native language, this might be a very nice feature, for some people who frequently access the docs from Google Search, but would like to read the docs in another language than their search engine language this causes the discomfort of having to select the desired language via the dropdown.

I am using Brave browser (Chromium) and Google Search for this.

### A possible solution?

Saving the selected locale into the _localeStorage_ and replacing the locale slug in the path, so the user gets redirected to the page with the selected language. This would cause an additional redirect when the link clicked does not matched the locale saved in local storage, but would (imo) create a better user experience when accessing the docs from google search. 

In case you would like me to further describe or if there is anything else just let me know. 

Cheers 👋

**Comment by TheOtterlord** [comment]
### Pros

- People who frequent pages on the docs site through links to specific documentation (Google, Discord, etc) can set their default language by navigating using the dropdown (saving the last language selected) and don't have to deal with changing the language to their preferred reading choice. An especially great benefit for those who do rely on translations for the docs wherever possible, since almost all links shared will link to the English version

### Cons

- Adds additional traction to Docs maintainers & translators trying to view specific translations
- People may find it confusing if they use both the English & another language depending on completeness of a translation?
- Web vitals / crawlers may find this to be a negative experience, thus impact SEO? (I'm no expert here though)

### Ideas

- To counter the cons, maybe we only redirect when the url doesn't include a locale (and maybe promote the sharing of links which are sans-locale through any share functionality. e.g. Discord docs search bot)
- Add a subtle option to allow redirections on other content (for those who want to see it in their preferred language in any context they use the docs, but without modifying the default docs experience)

**Comment by delucis** [comment]
I don't think we'll be able to change anything here unfortunately. Adding potentially unexpected, custom redirect behaviour to the site seems likely to cause more confusion even if it is what some percentage of readers might prefer. In general I'm in favour of letting users navigate explicitly to the content they want instead of trying to guess their preference (completely hypothetically we could have some complex user config modal with a "always redirect me to language X" option so it would be explicit but I'm not sure that UI complexity is that user friendly either).

I'm curious if anyone has examples of sites that do this in a way they like?

**Comment by vincentdorian** [comment]
Yeah, that does make sense to me. Also it would feel kinda counterintuitive clicking on a link, but ending up somewhere different.

I wonder though, if there's actually some other people that experience the same problem as me. 

I've spent some time finding some sites that use "routing based i18n", but they would all go about this the same way (for example [https://www.jetbrains.com/de-de/fleet/](https://www.jetbrains.com/de-de/fleet/), [https://ethereum.org/de/security/](https://ethereum.org/de/security/)).

So far, I did not find anything that handle it the proposed way.

**Comment by delucis** [comment]
Thanks again for raising this @vincentdorian! Always helpful to hear different perspectives and pain points even when we can’t figure out what to do about them 😅
