### ISSUE TITLE
Lit + Typescript example

### ISSUE THREAD

**Issue by JustinVoitel** [withastro/docs#324]
I can't seem to get a working example using lit typescript component. A example project or some documentation would be really appreciated!

**Comment by sarah11918** [comment]
Hi @JustinVoitel ! I'm making notes from the issues here, but I was wondering whether you had tried using this starter template example https://github.com/withastro/astro/tree/main/examples/framework-lit or opening the Lit example on https://astro.new ?

It would help us to know whether tyou tried but here's an issue with that example not working, or whether you just hadn't found that example yet.  :) Thank you!

**Comment by JustinVoitel** [comment]
Hi @sarah11918,
I was trying to get it to work locally and in a Stackblitz container, both unsuccessful!
Here you can try it our for yourself: https://stackblitz.com/edit/github-mo9936?file=src/components/Counter.ts
Some things I noticed:
- you can`t import 3rd party components (e.g the vaadin component in the example)
- some decorators throw an error (the customElement one in the example )

**Comment by sarah11918** [comment]
@JustinVoitel OK, so this is an issue with the example itself! Great to know!

If you happen to be on Discord, the best place to get info or help quickly on this is https://astro.build/chat

This repository is for our documentation, and it sounds like what you're experiencing is a problem with our starter template itself. So, you'd get the best eyes on the problem by filing an issue in the astro repository itself: https://github.com/withastro/astro/issues -- you could take a peek there and see if anyone has already reported anything. 

But most of our support (pretty quick and responsive!) happens in Discord, so if you are able to hop in there, someone should be able to at least have this conversation with you and maybe has more info about any underlying bugs right now, or knows about the specific starter itself. Otherwise, check out the Astro repo (not this one for documentation) because if anyone else has filed a bug or issue about this, it would be there.

So, I'm going to close this issue here since it's not a documentation issue, but rather an issue with Astro itself, and I hope you're OK to pick this up in one of the two places mentioned.  :)
