### ISSUE TITLE
Does the client:only directive still need a value?

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/docs#3309]
Hi there 🙋🏼 

## What? 
![image](https://github.com/withastro/docs/assets/10930234/a93f39c9-dce6-4f28-9fec-2a976498cb4b)

The [docs](https://docs.astro.build/en/reference/directives-reference/#clientonly), in many instances, mention that the `client:only` directive must be supplied a value, e.g., `client:only="react"`. 

Also, from the codebase (core, not docs), some error is supposed to be thrown when this is not the case because Astro needs a hint to use the correct renderer.

![image](https://github.com/withastro/docs/assets/10930234/df769635-ca27-4213-91d0-f69dd047f656)

A comment in the codebase specifically says: 
> ... Astro does not know (and **cannot guess**) which renderer to use and require a hint...

⚠️ In theory, I understand this. In practice (at least in dev), this does not seem to be true with the latest version of Astro.

> I haven't spent much time checking the source code, so I can't pinpoint what's happening here yet. Perhaps it's just some new update. 

### https://stackblitz.com/edit/github-c3x5hx?file=src%2Fpages%2Findex.astro

Visit the sandbox above. 
- A framework component (React) is rendered via the `client:only` template directive 
- The directive is used in 3 different ways 
    - `client:only` 
    -  `client:only='react'` 
    - `client:only='vue'` 

![image](https://github.com/withastro/docs/assets/10930234/d183f441-91df-4a0e-a87e-c39a1541b4c6)

The island is hydrated correctly with or without the framework value in all these. The island is even hydrated with the wrong framework as value, i.e., vue. 

 ## Is the hint still necessary? 
The million-dollar question ＄

**Comment by sarah11918** [comment]
OK @ohansemmanuel here's the scoop from the platform team!

- If your project only includes one UI Framework renderer (e.g. ONLY React, or ONLY Vue etc.) then that is *often* enough for Astro to infer which renderer you mean to use when using `client: only`.
- However, there are still *some* situations in which even knowing that you only have one renderer still required you to specify.
- This has not really been revisited since adding MDX support, which also works like a renderer behind the scenes. So, it's possible that even having only one renderer integration installed, plus having the MDX integration installed *could* require you to specify in `client: only`.

So, my assessment of the situation from a documentation standpoint is that we should continue to document that you should specify. It may not always be necessary, but it is not simple enough to explain when it's not necessary. And I think that only leads to more confusing documentation, and less helpful advice. 

If it happens to work for some situations without specifying, we'll treat that as a happy bonus. But the clear advice that will help everyone, in every situation, will be to say that they should (even "must"! even if sometimes that's a tiny lie) specify which renderer to use.

Thanks for exploring this! It would have been nice if this were no longer a necessary condition. But since it *somtimes* is,  with exceptions that are not simple to document, we're going to keep our existing advice.
