### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by matthewp** [withastro/docs#3311]
- Implementation PR: https://github.com/withastro/astro/pull/7067/
- Stage 3 proposal: https://github.com/withastro/roadmap/pull/587
- Stage 2 proposal: https://github.com/withastro/roadmap/issues/466 

## Needs

- API reference docs
- ? - This feature is most useful in SSG, so maybe it should go there? This feature does work in SSR as well, but you can already do redirects in SSR (manually) so it's not adding a new capability, just making one easier.

## How it works

You can add a top-level `redirects` config with keys that are from routes and the values are the to route. For example:

```js
import { defineConfig } from 'astro/config';

export default defineConfig({
  redirects: {
    '/api': '/docs/api'
  }
})
```

**Comment by matthewp** [comment]
API reference is being reviewed in the current PR. Is there an additional place we should document this feature?

**Comment by sarah11918** [comment]
Just making a quick note that in addition to docs for redirects explaining how to use them, we'll need to update:
- `api-reference` for `Astro.redirect()` which currently describes it as an SSR-only feature
- the SSR page which has an example of `Astro.redirect()` as an SSR feature (e.g. redirecting after logging in) - this is not *incorrect* usage, but it's listed here as an SSR feature which is now not correct.

Also, I think the best place for this content for now at least is on the Routing page. Since this is mostly an SSG feature (and we don't have an SSG page) but also can be used in SSR, and since it relates to (re)routing, that's my suggestion for where this content can go!

**Comment by sarah11918** [comment]
Yes, if it's no longer *exclusively* an SSR feature, which the RFC seemed to say. I think this can go with the new redirects content on the routing page.
