### ISSUE TITLE
Markdown content styling in a Markdown Layout does not match spec in documentation

### ISSUE THREAD

**Issue by kevinthenet** [withastro/docs#3485]
### What version of `astro` are you using?

2.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

When using [a Markdown frontmatter layout](https://docs.astro.build/en/guides/markdown-content/#frontmatter-layout), the [documentation describes](https://docs.astro.build/en/guides/styling/#markdown-styling) being able to use `<style>` tags OR imported stylesheets to style markdown content.  However, the only way the markdown content is _actually_ styled is through the use of imported stylesheets.

This could be mitigated by explaining the difference more clearly in the documentation or enabling styling markdown content in a layout using `<style>` tags as described in the documentation.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-aks7dp?file=src%2Flayouts%2FWorkLayout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kevinthemself** [comment]
Thanks!  I'll post below some of the confusion in the phrasing for the consideration of updating docs:

## Problem

While the documentation for Markdown Styling does specify "global styles", I would argue the preceding sentence muddles up the meaning:

> Any Astro styling methods are available to a [Markdown layout component](https://docs.astro.build/en/core-concepts/layouts/#markdownmdx-layouts).

1. Scoped styles (e.g. creating a CSS rules for `p` tags in the layout component) do not work since rendered Markdown content does not have the class for the parent layout component, so I don't think "any" really applies here.
2. On a general note, [global rules do work and are encouraged for CMS style content that lives _outside_ of Astro](https://docs.astro.build/en/guides/styling/#global-styles), however I wouldn't categorize Markdown content from a Content Collection as living outside of Astro, since it's part of the Astro ecosystem, though that could be a misinterpretation on my part. Nonetheless, it's another part of the confusion.
3. Imported stylesheets seem to be the best and simplest way of applying stylings to rendered content within a Markdown Layout without having to resort to global styles. I think this is key to call out because having to understand why the layout classes aren't applied to rendered markdown content should not be something the typical user needs to understand.

All in all, to me, content rendered within the layout should include the stylings applied to the layout. I understand this is not the case, but I imagine others might similarly intuit my interpretation.

At issue is in part how markdown content is rendered on the page and partly the cascading order of stylings within Astro.

## Suggestion
I would suggest rephrasing the Markdown Styling section to something along these lines:

> Any Astro styling methods are available to a [Markdown layout component](https://docs.astro.build/en/core-concepts/layouts/#markdownmdx-layouts). Please note that layout styling is **not** the same as the rendered Markdown content styling.

> You can apply global stylings to your rendered Markdown content by adding [<style is:global> tags](https://docs.astro.build/en/guides/styling/#global-styles) and/or [imported stylesheets](https://docs.astro.build/en/guides/styling/#external-styles) to the layout that wraps your page content. Imported stylesheets are the simplest way to _only_ apply stylings to rendered page content, however are still subject to [Astro's cascading order](https://docs.astro.build/en/guides/styling/#cascading-order).

`src/styles/imported-stylesheet.css`
```css
/* This rule will apply only to the rendered Markdown on the page */
article p {
  color: red;
}
```

`src/layouts/markdown-layout.astro`
```astro
---
import '../styles/imported-stylesheet.css';
---

<article>
  <slot />
</article>

<style is:global>
/* alternatively, you can use global style rules which will always appear last in order of appearance */
/* however, this rule would apply to all pages, which may not be ideal */
article p {
  color: blue;
}
</style>
```

> You can also add [CSS integrations](https://docs.astro.build/en/guides/styling/#css-integrations) including [Tailwind](https://docs.astro.build/en/guides/integrations-guide/tailwind/). If you are using Tailwind, the [typography plugin](https://tailwindcss.com/docs/typography-plugin) can be useful for styling Markdown.

Hope that clarifies a bit further how this might cause issues for others who read the documentation in a similar way that I did.

**Comment by kevinthenet** [comment]
Very good, I'll create a PR for this soon.

**Comment by kevinthenet** [comment]
@delucis and @sarah11918 Apologies for the delay, haven't had a lot of bandwidth to sit down and get this done, but I just opened up the small PR with the changes described.
