### ISSUE TITLE
 [OTHER] - Update section on data fetching

### ISSUE THREAD

**Issue by sasoria** [withastro/docs#3648]
### 📋 Explain your issue

The section about [data fetching](https://docs.astro.build/en/guides/data-fetching/) starts off by stating that ".astro files can fetch remote data at build time to help generate your pages" and in the subsection about fetching in Astro components it says: "if SSR mode is enabled, any fetch calls will be executed at runtime".

Maybe we could mention the part about SSR in the starting paragraph? If this was intentional because Astro is a SSG first meta-framework or for some other issue with framework components, then that's understandable!

## Screenshot
![Screenshot 2023-07-03 at 17 22 51](https://github.com/withastro/docs/assets/7903076/7b57ad0c-2278-457e-ab55-4215d7e83573)

**Comment by ElianCodes** [comment]
Not sure what other Maintainers think about this, but I would keep it this way, since Astro is based on more of a opt-in design  instead of an opt-out design.

**Comment by sasoria** [comment]
That makes sense!

**Comment by sarah11918** [comment]
Thanks for this @sasoria ! It's actually on my list for this quarter to tackle SSR docs in general, and sprinkling in mention on all other pages it makes sense, vs just having on single SSR page. I think you've identified a real weakness as we went from SSR being experimental, to A Proper Thing, to now a quite common use case!

Elian is also correct: we do think of SSG as the default because SSR requires opting in. But, one change we've made elsewhere in the docs is to change wording from "at build time" (which is VERY SSG focused) to "at render time" which is a little looser and *is* basically at build time for SSR sites, but is also at on-demand generation for SSR sites. A wording change in that direction might help here? Do you think something like that would make sense?

**Comment by sasoria** [comment]
Yes, I think "at render time" would be an improvement. I found the current opening sentence in the section about data fetching confusing from a SSR point of view.

**Comment by delucis** [comment]
@TheOtterlord suggested:
> `.astro` files can fetch remote data to help you generate your pages
Someone want to PR that change?
