### ISSUE TITLE
Better explanation for "Fragments & Multiple Elements"

### ISSUE THREAD

**Issue by Rolanddoda** [withastro/docs#369]
I am reading the docs and I stumbled here:

![image](https://user-images.githubusercontent.com/18482346/164936777-fcb7b520-8728-424c-b1e9-cdb99ff707b7.png)

The first section(Dynamic HTML) is easy to understand.

The second section though, it's a bit confusing. Compared to the first one, it has multiple elements.
So at first, I thought that when "looping", if I have to display HTML with a single root element I write it as is. However, if I have to write multiple root elements I must wrap them inside a Fragment.

**But is true??**

In `index.astro` I pasted the code from the Docs and removed the Fragments:

```html
<ul>
  {items.map((item) => (
    <li>Red {item}</li>
    <li>Blue {item}</li>
    <li>Green {item}</li>
  ))}
</ul>
```

And everything seems to be working fine without any issue.

So either the docs should get updated or it's a bug (but since it works why does it have to be a bug?)

**Comment by sarah11918** [comment]
Hey, thanks for this @Rolanddoda !

Yes, I *am* surprised that what you wrote works... 😅  I will get people confirming that behaviour!

The distinction intended is that when writing something that looks like JSX/JS, the return value should be a single element, like it should be in JSX. (It doesn't *have* to be a fragment specifically. A div, or a <ul> or any single element should work.) 

So what you describe as your "first thought" is absolutely the intended behaviour! That's what we indend, and that's why the docs say what they do! And, I know people with past versions of Astro have had problems when they did NOT do that.

So.... why is it working now? That's unusual, and I don't know why! I'll get people looking into that. :)

Thanks for bringing this up!

**Comment by Rolanddoda** [comment]
Wow, @sarah11918 such a quick response and it's Saturday! Thank you.

**Comment by victor0x16** [comment]
hey, I can confirm that behaviour, see:

```astro
// Works as expected
---
const items = ["Dog", "Cat", "Platipus"];
---
<ul>
  {items.map((item) => (
    <>
      <li>Red {item}</li>
      <li>Blue {item}</li>
      <li>Green {item}</li>
    </>
  ))}
</ul>
```
and this also works but it should?
```astro
 {items.map((item) => (
      <li>Red {item}</li>
      <li>Blue {item}</li>
      <li>Green {item}</li>
  ))}
```
Although it generates a slightly different js output on [Astro Play](https://astro.build/play). I don't know why :(

**Comment by sarah11918** [comment]
I am again playing around with this too... inside components, rendered on a page, and yeah, I can only conclude that it does work. Maybe Astro is just that good now.  :)

Just wanted to check in to say I haven't forgotten this one! I'm waiting before changing any documentation until I get guidance from core that this isn't some weird or unexpected behaviour, or caused by something temporary. It's on the list of things they have to look at! (But, their list is long!)  :)

**Comment by sarah11918** [comment]
@delucis If we're finding that "must" isn't entirely necessary, then what if we change this example to demonstrate a case where we might WANT to use Fragment (I think you just had a support thread where you explained using a directive...) rather than a situation where you MUST use Fragment.

That way, we keep an example of using Fragment, and bonus points, show a directive in use. IF we start to get support comments where it becomes clear that people ARE needing to use a fragment for this typical JSX-y stuff, we revert to more strong wording then?

**Comment by inwardmovement** [comment]
See also https://github.com/withastro/docs/discussions/722

**Comment by sarah11918** [comment]
Sounds like we have a strategy then! We will:
1. Ask Nate what the heck is going on during our Docs call today. 😅 
2. Change the example with a fragment to a more USEFUL one (ie with a client:* directive) showing why you might use a Fragment (maybe the same one from #722 )
3. Wait to see people having trouble in support because they DIDN'T use a fragment to wrap multiple items
4. .... profit!
