### ISSUE TITLE
How can I use Astro.js to send the request on the client?

### ISSUE THREAD

**Issue by liaoyio** [withastro/docs#4126]
I need to send a request on the homepage of my webpage, hoping to request a new request every time the page is refreshed, rather than generating static data during project construction. How can I use Astro.js to send the request on the client?

**Comment by vcotir** [comment]
Hey @liaoyio, it sounds like what you're talking about is sending a request on the client side on page refresh? 


I think you want to look into this: https://docs.astro.build/en/guides/data-fetching/

<img width="804" alt="image" src="https://github.com/withastro/docs/assets/20938052/86534861-ea62-4638-8058-16eecdb02b6f">

**Comment by sarah11918** [comment]
Hi @liaoyio! I hope the link provided to you was helpful! I am closing this issue because this is not the place for support questions. This is for reporting problems with our documentation, and the only people reading these issues are people working on our documentation site.

If you still have questions or need any help, please visit our Discord https://astro.build/chat and post a question in our support forum! People will be happy to help you get this working there!
