### ISSUE TITLE
Fix "Static site generation" code documentation

### ISSUE THREAD

**Issue by andrewmosby** [withastro/docs#4155]
https://github.com/withastro/docs/blob/371a48d8fbf95923d583fb1f639ced74f0ebc2eb/src/content/docs/en/guides/cms/storyblok.mdx#L429

Stepping through this documentation at this step results in an error that "This record could not be found."

Updating this line to `cdn/stories/blog/${slug}` fixes the issue.

**Comment by vcotir** [comment]
I tried the same thing and confirmed this is true! I got 404 when the lined wasn't updated. 

Explanation: 
The Storyblok blog guide section tells the user to create a "blog/astro-is-amazing" entry within a "Blog" folder. 
[<img width="808" alt="image" src="https://github.com/withastro/docs/assets/20938052/3d043916-2a13-4d92-b7ae-0d56882b9602">](https://github.com/withastro/docs/blob/371a48d8fbf95923d583fb1f639ced74f0ebc2eb/src/content/docs/en/guides/cms/storyblok.mdx#L255)

Doing so results the creation of a story with the name "blog/astro-is-amazing" where the slug is "astro-is-amazing". 
<img width="1082" alt="image" src="https://github.com/withastro/docs/assets/20938052/b15cfa5d-3572-496a-8fad-ffe2cda23d8b">

But to access the content via API, the full slug must be used. And since the story entry "blog/astro-is-amazing" has a slug of "astro-is-amazing" and the story entry is nested within "blog", the full slug is "blog/astro-is-amazing".

Therefore, because the guide tells the user to create a "blog/astro-is-amazing" story entry nested inside of a "Blog" folder, the request to storyblok must be `cdn/stories/blog/${slug}` as @andrewmosby suggests.

<img width="429" alt="image" src="https://github.com/withastro/docs/assets/20938052/351f8c6c-705e-4d9e-bafd-6fd4b9224094">

**Comment by sarah11918** [comment]
Thanks for spotting this @andrewmosby , and thanks for confirming the behavior @vcotir !

We would be happy to receive a PR to fix this line in the docs! If either of you would like to make one, you can check out our CONTRIBUTING.md guide for extra information. The page in docs itself  will have an "edit this page" menu item in the sidebar you can use to take you to the proper file directly in our repository.  🙌

**Comment by vcotir** [comment]
Thanks, @sarah11918! PR here: #4279
