### ISSUE TITLE
Add `HTMLTag` to TypeScript guide

### ISSUE THREAD

**Issue by natemoo-re** [withastro/docs#4169]
### 📚 Subject area/topic

TypeScript

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/typescript

### 📋 General description or bullet points (if proposing new content)

We don't currently document the `HTMLTag` type.

- `HTMLTag` is essentially a built-in type of all the known HTML elements
- Using this type instead of `string` allows for better attribute completion, because we know for a fact that common attributes are supported.
- As outlined in https://github.com/withastro/astro/issues/8024, this type can be used to avoid some type errors with attributes like `id`.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

N/A

**Comment by piratey7007** [comment]
Hi @natemoo-re, I saw this issue and was looking through the documentation. It looks like there's been [some documentation](https://docs.astro.build/en/guides/typescript/#polymorphic-type) possibly added since you opened the issue in August (though it may have been there earlier). It showcases a standard use-case for the `HTMLTag` type, but doesn't iterate much past that. 

I was wondering what you thought about this issue, and if the need still exists to further document this type.

**Comment by sarah11918** [comment]
Closing this as we have `HTMLTag` now, but if it's not sufficient, feel free to reopen with more details!
