### ISSUE TITLE
French documentation on Component Props contains errors

### ISSUE THREAD

**Issue by MattCrl** [withastro/docs#4175]
French documentation on this page (https://docs.astro.build/fr/core-concepts/astro-components/#props-de-composant) seems to be incorrect. 

**After the Typescript Props interface there's a code sample showing "style" tags that shouldn't be there :** 
```
---
// Votre script du composant ici !
---
<style>
  /* restreint au composant, les autres balises H1 sur la page restent les mêmes */
  h1 { color: red };
</style>

<h1>Hello, world!</h1>
```
**If I switch to English documentation that's the correct code sample of Typescript Props interface :** 
```
---
interface Props {
  name: string;
  greeting?: string;
}

const { greeting = "Hello", name } = Astro.props;
---
<h2>{greeting}, {name}!</h2>
```

**Comment by delucis** [comment]
Thanks for the issue @MattCrl! Looks like the French translation of that page was last updated in January but we’ve made some changes to the English version since then: https://github.com/withastro/docs/commits/main/src/content/docs/en/core-concepts/astro-components.mdx?since=2023-01-13T22:05:10.000Z

Would you be interested in making PR to update it?
