### ISSUE TITLE
Screen Reader Accessibility Issue on Main Documentation Page

### ISSUE THREAD

**Issue by BaraaNazar** [withastro/docs#4211]
### 📝 Issue Description

When using a screen reader on the page https://docs.astro.build/en/getting-started/, the screen reader initiates its reading from an unexpected location – specifically, the bottom of the sidebar. This behavior is inconsistent with the intended reading order and creates a usability issue for users relying on screen readers.

### 📋 On which page(s) it occurs

https://docs.astro.build/en/getting-started/

### 🤔 Expected Behavior

When navigating the page https://docs.astro.build/en/getting-started/ with a screen reader, the expected behavior is for the screen reader to start reading from the beginning of the page, specifically from the section titled "What is Astro?":
"Astro is an all-in-one web framework for building fast, content-focused websites..."

### 👀 Current Behavior

But, instead, the screen reader initiates its reading from an unexpected location – specifically, the bottom of the sidebar.

### 🖥️ Browser

Microsoft Edge

```[tasklist]
### Tasks
```

**Comment by sarah11918** [comment]
Thank you for mentioning this @BaraaNazar ! This is obviously something we'd like to prioritize, so I will make sure @Yan-Thomas is aware and can take a look at this, and then give you guidance on how you can contribute to help with a fix!

**Comment by BaraaNazar** [comment]
let me provide more details on this issue:
- The OS: macOS 13.4.1
- the browser: Microsoft Edge and Chrome
- the screen reader: built-in screen reader in the same browsers above (Read Aloud in Microsoft Edge). 
- how did I find this issue: I opened the docs in the browser and went to the Astro docs page (link: https://docs.astro.build/en/getting-started/) and then I clicked on the read-aloud button or by using the keyboard shortcut (shift + command + U).

**Comment by Yan-Thomas** [comment]
Thanks for reporting this @BaraaNazar, and sorry for the wait! 

I found out the root issue is because Edge's Read Aloud doesn't properly parse the DOM and the corresponding Accessibility Tree of the page, nor account for `aria-*` attributes. From my research, it isn't meant as a screen reader, so I believe Apple's Voice Over would be more helpful if that's your need.

To give more detail, we have a "Give us feedback" modal with a `<h1>` which is semantically correct for being in a separate context, but Read Aloud will only look for the first `<h1>`, causing the issue.

If you're only using it as a reading feature, a valid workaround would be to right-click into the page's heading (e.g. Getting Started) and start Read Aloud from there, and it will respect the proper reading order.

We were already thinking about removing or redesigning the component that causes this Edge-specific issue, so rest assured that we're not going to just ignore the issue, but fix it in a different way.

**Comment by sarah11918** [comment]
Closing this as we are migrating to Starlight, which will be a different infrastructure.
