### ISSUE TITLE
missing assets import

### ISSUE THREAD

**Issue by dotarjun** [withastro/docs#4325]
### 📝 Issue Description

It's much more comprehensive to mention that 
1. The user must import Image from "astro:assets" first
2. Then Replace ``<img />`` with ``<Image/>``

I'd like to be assigned to this.  

### 📋 On which page(s) it occurs

https://docs.astro.build/en/guides/assets/#update-existing-img-tags

### 🤔 Expected Behavior

The docs to guide in a much more intuitive way. Also, when I finish *Update existing ``<img>`` tags* section, then I expected the image to be working but it wasn't.

### 👀 Current Behavior

Confusing docs

### 🖥️ Browser

Edge

**Comment by sarah11918** [comment]
Hi ! This section is about only updating from old `<img>` tag to new `<img>` tag, because the imported image shape has changed and if you want to continue to use `<img>` then you must add `.src` to the image's attribute. This is not instructions for changing `<img>` to the `<Image /> component, so no import is necessary here! I hope that helps you!

And, this page will be removed for v3.0 when `astro:assets` is no longer experimental, so we are not accepting PRs for this deprecated page at this time.

Please feel free to file an issue if you spot any problems with the new documentation after 3.0 launch!  :raised_hands:
