### ISSUE TITLE
Bun isn't experimental anymore (?)

### ISSUE THREAD

**Issue by 11Firefox11** [withastro/docs#4601]
### 📚 Subject area/topic

runtimes

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/bun/

### 📋 General description or bullet points (if proposing new content)

Bun is now production ready and [Astro is fully supported](https://bun.sh/blog/bun-v1.0#changelog-since-v0-8).
I suppose the text "Using Bun with Astro still is experimental" can be removed.

**Comment by lilnasy** [comment]
This is accurate as _using Bun with Astro_ still is experimental.

And official support for bun is not on the roadmap. Ideally, astro maintainers would focus on astro itself rather than the adapters. I think it should be upto the bun community to maintain this in the long term as they will be better equipped to make best use of the runtime.
