### ISSUE TITLE
CSS style ignored when setting className to React component

### ISSUE THREAD

**Issue by yanickrochon** [withastro/docs#4697]
This `.astro` component applies the correct styles for `title`, however the `code` class name is set to the React component, no style is applied.

```astro
<style>
  .title {
    color: rgba(220, 220, 220, 0.8);
    background-color: #282a36;
    font-size: 80%;
    font-style: italic;
    padding: 2px 10px 4px 10px;
  }
  .code {
    border: 1px solid white;
  }
</style>

<div class="title">{title}</div>
<RawHtml className="code" html={html} />
```

This was also tried and ignored by Astro

```astro
<style>
  .code .title {
    color: rgba(220, 220, 220, 0.8);
    background-color: #282a36;
    font-size: 80%;
    font-style: italic;
    padding: 2px 10px 4px 10px;
  }
  .code pre {
    border: 1px solid yellow;
  }
</style>

<div class="code">
  <div class="title">{title}</div>
  <RawHtml html={html} />
</div>
```
(The variable `html` contains a `pre` element, no style is applied to it.)

**Comment by DavidEGiraldo** [comment]
The issue here is that Astro doesn't let you use the `className` attribute directly. Plus, in both Astro and React, HTML attributes like `class` don't automatically get passed to child components. However, you can work around this by using the `class` attribute, but you'll need to receive it as a `prop` in your React component and then apply it within the component. It's kind of like what they explain in [this part of the documentation](https://docs.astro.build/en/guides/styling/#passing-a-class-to-a-child-component). 
If you have more questions like this, consider joining the [Discord chat](https://astro.build/chat), where the community can provide you with assistance.

**Comment by sarah11918** [comment]
Thank you for stepping up and helping with the answer and supporting links, @DavidEGiraldo !  🙌 

@yanickrochon, please do consult our documentation and visit our Discord for support questions. This repository is for issues related to our Astro Docs site, and this is not the place for support with your own code. We have support members on Discord ready to help, but these issues are only for reporting problems with our documentation.  See you on Discord!  🚀
