### ISSUE TITLE
Add Typescript example for `Using one Layout for .md, .mdx, and .astro`

### ISSUE THREAD

**Issue by pReya** [withastro/docs#4763]
### 📚 Subject area/topic

Layouts

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/core-concepts/layouts/#using-one-layout-for-md-mdx-and-astro

### 📋 General description or bullet points (if proposing new content)

The docs explain that a Layout can be used both, to pass props via `.md/mdx` files and via "Component syntax", e.g.

```mdx
layout: MyLayout.astro
myProp: "some value"
```

or alternatively

```jsx
<MyLayout myProp={"some value"} />
```
The docs say this can be achieved like this:

```plaintext
---
const { title } = Astro.props.frontmatter || Astro.props;
---
<html>
  <head></head>
  <body>
    <h1>{title}</h1>
    <slot />
  </body>
</html>
```
However, the docs do not describe how to type this example. Using the given example in a TypeScript project will throw all kinds of `tsc` errors.

It would be very nice if someone could add a TS example for this snippet.

Here's my naive and non-working approach:

```
---
import type { MarkdownLayoutProps } from "astro";

interface Props {
  title: string;
  frontmatter: MarkdownLayoutProps<{ title: string }>;
}

const { title } = Astro.props.frontmatter || Astro.props;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body>
    <h1>{title}</h1>
    <slot />
  </body>
</html>
```

I'd be happy to contribute a PR to the docs, if someone points me in the right direction of how to solve this properly in TS.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Can't reproduce in Stackblitz (can't install `@astro/check` and/or `typescript` due to old Node 16 version in StackBlitz templates)

**Comment by piratey7007** [comment]
Hey there @pReya. I was messing around a bit with it, but I don't typically use markdown that much. Let me know if the following solutions work for you.

```astro
---
import type { MarkdownLayoutProps } from "astro";

type Props = MarkdownLayoutProps<{ title?: string }> & {
  title?: string;
};

const { title } = Astro.props.frontmatter || Astro.props;
---

<html>
  <head></head>
  <body>
    <h1>{title}</h1>
    <slot />
  </body>
</html>
```

A type helper to merge the types could also be helpful here, if you're using this often especially, or you have a lot of props.

```astro
---
import type { MarkdownLayoutProps } from "astro";

type FrontmatterOrAstroProps<T extends Record<string, any>> = MarkdownLayoutProps<T> & T

type Props = FrontmatterOrAstroProps<{
  title?: string;
}>

const { title } = Astro.props.frontmatter || Astro.props;
---

<html>
  <head></head>
  <body>
    <h1>{title}</h1>
    <slot />
  </body>
</html>

```

**Comment by piratey7007** [comment]
I stand corrected actually. It's a bit messier than I thought initially, especially trying to keep the luxury of destructured sytnax. I did find a solution however, though please do share if you have any problems:

```astro
---
import type { MarkdownLayoutProps } from "astro";

type Props = MarkdownLayoutProps<{
  title?: string
}> | {
  title?: string
};

// Or using a type helper
type FrontmatterOrAstroProps<T extends Record<string, unknown>> = T | MarkdownLayoutProps<T>;

type Props = FrontmatterOrAstroProps<{
  title?: string
}>;

const { title } =
  "frontmatter" in Astro.props ? Astro.props.frontmatter : Astro.props;
---

<html>
  <head></head>
  <body>
    <h1>{title}</h1>
    <slot />
  </body>
</html>
```

The primary difference here from earlier is this gem I found 

```ts
const { ...props } = "frontmatter" in Astro.props ? Astro.props.frontmatter : Astro.props;
```  

But also opting for the union type instead of an intersection type.

All that to say, this is how I would do it, and after spending 30 minutes sitting here scratching my head figuring it out, it's probably a good idea to add this to the docs.

**Comment by pReya** [comment]
Thanks for the late reply and your answer. I'm not sure I understand this line completely:

```
const { ...props } = "frontmatter" in Astro.props ? Astro.props.frontmatter : Astro.props;
```

Can you elaborate how this works?

**Comment by piratey7007** [comment]
Hey there @pReya, no problem, and gladly.

The way that the `MarkdownLayoutProps` type works is it basically moves the properties you define into an inner property called `frontmatter`. So `{ title: string }` turns into `{ frontmatter: { title: string } }`. So we need to allow both to be independently valid.

Logically, since it tries pulling from the `frontmatter` prop as well as from `Astro.props`, the following syntax will work in JS:

```js
const { title } = Astro.props.frontmatter || Astro.props;
```

But because of a quirk in the way that TypeScript infers types, and the way that MarkdownLayoutProps works under the hood, TypeScript just plain doesn't like this, and doesn't infer correctly. My solution was this:

```ts
const { title } = "frontmatter" in Astro.props ? Astro.props.frontmatter : Astro.props;
```

Or in pseudo-code:

```sh
We have a variable "props".
if "frontmatter" is a key on "Astro.props"
    then we set "props" to "Astro.props.frontmatter" (which is markdown properties)
else
    then we set "props" to "Astro.props" (which is the Astro component properties)
```

And TypeScript correctly infers types (as far as I've been able to tell), because this tells TypeScript "We're *officially* testing if we're pulling from frontmatter or not, so based on that, you can infer types." Whereas before, it appears to act as if it was unknown types, probably as a result of using `||` syntax.

I'm not an expert on TypeScript, but that's what it looks like to me at least, and this solution solved that for me.

**Comment by sarah11918** [comment]
Hi! I can see that you solved this for your own setup, and that's great! We don't have plans to update that particular example to TypeScript, although we currently are looking at some options for providing more TypeScript examples throughout the docs, and how to do that alongside JavaScript.

So, I'll close this issue now as it's not something directly we're working on, but thank you for pointing this out and posting your solution so that it can be searched and discovered by others!  🙌
