### ISSUE TITLE
Add note about including .astro files in tsconfig when using Path Aliases

### ISSUE THREAD

**Issue by Mitsunee** [withastro/docs#4802]
### 📚 Subject area/topic

Import Aliases

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/aliases/
Possibly also https://docs.astro.build/en/guides/typescript/

### 📋 General description or bullet points (if proposing new content)

In order for the VSCode Extension to correctly typecheck `.astro` files they must be included in the `"include"` array in `tsconfig.json` such as this:

```diff
 {
   "extends": "astro/tsconfigs/base",
   "compilerOptions": {
     "baseUrl": ".",
     "paths": {
       "~/*": ["./src/*"]
     }
   },
   "include": [
     "src/env.d.ts",
     "**/*.ts",
     "**/*.tsx",
+    "**/*.astro"
   ]
 }
```

Not having `.astro` files included results in broken Path Aliases in VSCode. `astro check` and `tsc` will not have any issues either way, but it might still be nice to mention this in the docs, since you are already mentioning VSCode and the extension there there.

![Screenshot_20230924_222632](https://github.com/withastro/docs/assets/19474909/3f701ad0-e1db-40b2-bc16-e0ca630bc72d)

I am unsure if anything else breaks, I only saw problems with imports and that my svg file imports are now `ImageMetaData` (which suggests that types were still checked and only aliased imports were affected) as of 3.0.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Can't really provide a repro as this is about behaviour exclusive to the Astro VS Code Extension.

**Comment by newtoallofthis123** [comment]
Hmmm....I never really faced this issue while I was working with Astro. What typescript config are you using? is it strictest?

**Comment by Mitsunee** [comment]
I provided an abridged version of my config above, it overrides the extended config

**Comment by Mitsunee** [comment]
> I added the path aliases like you did, but didn't add the include key. VS Code isn't showing any errors for me.

So basically you made a blank project and didn't do the thing I'm reporting about? Why ping me then?

**Comment by delucis** [comment]
Please be more polite in your interactions here @Mitsunee. Our https://github.com/withastro/.github/blob/main/CODE_OF_CONDUCT.md applies to all discussions in the `withastro` GitHub org. We expect everyone to show empathy and respect.

---

Regarding your report, in general, `include` is not recommended as it disables TypeScript’s default ability to discover types, limiting the project to ONLY exactly the path inside `include`. This forces manual updates when new paths are added to a project. If you remove the `include` array from your `tsconfig.json` as shown by @dreyfus92, things should work as expected.

**Comment by sarah11918** [comment]
@Mitsunee In addition to reminding you of our expectations that people will react politely here, I will also take this opportunity to remind everyone that it is expected that people will try things related to any issue reported and report back here whatever they experience

When people report errors, we rely on other community members to also report their experiences so we can narrow down results. This is absolutely expected behaviour from our community, and in this case, now we have a report of someone not getting errors without needing the solution you proposed. 

Reports like this are essential before docs editors get involved so that we can figure out whether something experienced and reported by one person is in fact reproducible and happening in general. We are appreciative of everyone's reports so we can figure out whether something does in fact require a change in documentation, or whether there is instead a bug that needs fixing (where our policy is NOT to change documentation, but to fix the bug!), or whether in fact something else might be happening that is more a support issue than a general behaviour.

I will note that you were mentioned so that you could provide additional information, because one of our docs members was unable to replicate your problem and was attempting to diagnose further. I consider this a reasonable use of a mention, and I hope you can also see there was a good-faith attempt to understand your situation further in order to assist.

It would seem that with both a counter example, and receiving information that what you propose is in fact not recommended practice, that this issue should be closed as a documentation issue. I'm sure people would be more than happy to help in the Astro Discord if you would like to troubleshoot further why you're not experiencing the intended and expected behavior. Do you feel there is any reason to keep this issue open, or have more information to add?

**Comment by Mitsunee** [comment]
Nobody in this issue has actually tried what I am talking about. I didn't ask for a damn essay either. Open source is doomed if all I ever get is nonsense like this because nobody wants to read the text I wrote above and just rejects me without even trying what I reported. This keeps happening.

Again: Not having "**/*.astro" in the includes array causes the behavior in the screenshot and not putting the key is not a solution because there will be other people who wish to manually configure things and need this information.

**Comment by Mitsunee** [comment]
> Regarding your report, in general, `include` is not recommended as it disables TypeScript’s default ability to discover types, limiting the project to ONLY exactly the path inside `include`. This forces manual updates when new paths are added to a project. If you remove the `include` array from your `tsconfig.json` as shown by @dreyfus92, things should work as expected.

The "includes" array needs to be configured correctly. That is the entire point I'm trying to make here. Not configuring it to include astro files breaks the VSCode extension and possibly other things.

**Comment by delucis** [comment]
> The "includes" array needs to be configured correctly. That is the entire point I'm trying to make here. Not configuring it to include astro files breaks the VSCode extension and possibly other things.

That’s true, but in docs we need to make judgement calls about what to include (pun not intended) and what not to include. If someone opts in to using TypeScript’s `include` option, they inevitably have to explicitly `include` any files they want TypeScript to work in — as is the case when using `include` in any TypeScript project (this is not Astro-specific). We don’t recommend using `include` for this reason. I think it would be confusing for the Aliases (or TypeScript) guide to document needing to add something to an array we’ve never recommended people use in the first place.

**Comment by Mitsunee** [comment]
There are plenty of reasons for why one might want to configure the includes option, especially with something as slow as typescript's typechecker, which is why I thought it might be good to mention this in the docs like "If you are using `"includes"` make sure to add astro files there".

"Don't use this" is both terrible advice (not ever using something means you will never learn about it either) and a very silly reason to deny something I had problems with for months until someone unrelated on mastodon guessed their way into the solution I missed and would've known to check for if your docs had mentioned this. I could've just as well opened a ticket on withastro/astro about this had I not gotten the solution by someone else guessing on social media.

There's seemingly a disconnect here between letting users configure their stuff the way they wish and you asking users to stick to what's "recommended". Personally I thought a guide is there to guide me to my preferred solution, not yours.
