### ISSUE TITLE
⚠️ Issue

### ISSUE THREAD

**Issue by matto2** [withastro/docs#4879]
In the blog tutorial > src/components/Social.astro I'm having an issue with the ".com" being hardcoded in the component. It works fine as long as the social ends in .com, but for 'threads' for example, it fails because the domain ends in .net

**Comment by TheOtterlord** [comment]
I'm not sure how important it is to change this in the blog tutorial directly, but here's a quick change if you want to add it to your site. You can take in a prop named `href`. If that prop exists, use it as the href. Otherwise, create it using platform. I've used the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) in this example, but you could also do this inside the component script.

```astro
---
const { platform, username, href } = Astro.props
---

<a href={href ?? `https://www.${platform}.com/${username}`}>{platform}</a>

<style>
  a {
    padding: 0.5rem 1rem;
    color: white;
    background-color: #4c1d95;
    text-decoration: none;
  }
</style>
```

**Comment by matto2** [comment]
Thanks!

**Comment by sarah11918** [comment]
Looks like this was solved, so I'm going to close this issue! I'm glad you found a solution that worked for you!
