### ISSUE TITLE
Add a glossary page

### ISSUE THREAD

**Issue by Genteure** [withastro/docs#5035]
### 📋 Explain your issue

A glossary page gives a clear definition to terminologies used in the project, helps people communicate more clearly and avoid misunderstanding.
A translated glossary page with a translation-to-English term mapping is even more helpful to other language speakers, it provides a convenient location for users to check for the correct wording, thus enable easier communication with the larger community.

Examples of glossary page in other projects:

Vue:

- https://vuejs.org/glossary/
- https://ja.vuejs.org/glossary/
- https://cn.vuejs.org/glossary/

Python:

- https://docs.python.org/3/glossary.html
- https://docs.python.org/zh-cn/3/glossary.html
- https://docs.python.org/ko/3/glossary.html

**Comment by ShikhaaT44** [comment]
I am interested in working on this issue. Please assign me this issue so I can get started.
PS - Please provide an index or some major pointers for pages i should focus on for crucial terminologies.
Thank you

**Comment by sarah11918** [comment]
Hi @Genteure 

I think this could be a really useful addition, though it's a huge undertaking. I would be happy to see the community kick this off, so I've added some labels to encourage participation. I might even send out a  `team-docs` alert on this one! I can probably provide some oversight and answer questions, but we are, and have obviously been really working hard on Astro v4.0 and the docs Starlight migration, so this isn't something I've been able to personally take on as a project.

No reason why our fabulous community can't get started without me, though!  ;)

@ShikhaaT44 , we do not assign issues to community members in this repo. Everyone is free to work on whatever they like, but they should communicate what they are doing so that the community is aware.

**Comment by VoxelMC** [comment]
I love this idea! Can't wait to assist in finding terms :)

**Comment by vasfvitor** [comment]
@VoxelMC lets start then, we can open a thread on discord and leave a link here or @Genteure could open a PR and everyone can leave a suggestion there

Terms: static, server, and hybrid rendering. And in context SSR and SSG

Now, I'm wondering if could be dynamic generated from various pages with a special "Definition" component and organized in the Glossary. Maybe the component could query the terms from a json to make sure it's up to date

**Comment by Genteure** [comment]
I just created [a thread in `#docs`](https://discord.com/channels/830184174198718474/853350631389265940/threads/1177958355189387294) on [discord](https://astro.build/chat), feel free to chime in! You are also welcome to leave suggestions here, I believe it's important to make sure using discord is not a requirement to participate.

---

> Now, I'm wondering if could be dynamic generated from various pages with a special "Definition" component and organized in the Glossary. Maybe the component could query the terms from a json to make sure it's up to date

Good idea! We maybe can use content collections for this.

**Comment by sarah11918** [comment]
UPDATE!  We've just created a `glossary.md` file here: https://github.com/withastro/docs/blob/main/contributor-guides/glossary.md

**Comment by sarah11918** [comment]
I'm going to close this issue since we have a group/process now!  :partying_face: !!

For anyone finding this, you can visit the Discord link in this thread and join in!
