### ISSUE TITLE
Support for inspect debug in VsCode

### ISSUE THREAD

**Issue by thiagocorbalan** [withastro/docs#5151]
Hello,

Recently i trying to configure my vscode to attach process astro in development mode, but not find support for exposing port to debug mode, in none documentation i find this configuration. Do we have somenthing configuration for this?

Ex. `astro dev --inspect=0.0.0.0:7000` example for configuration in evironment docker

**Comment by sarah11918** [comment]
Hi @thiagocorbalan ! These issues are for issues with the Astro documentation. For support with your project, please join us in Discord at https://astro.build/chat -- that's where community members are able to look at questions and help you out. Then, if it turns out that there's something to fix in documentation, then our support squad lets us know, or you can come back here and let us know what should be added. Unfortunately, we aren't able to help with this question here, so we suggest you ask in our Discord support!
