### ISSUE TITLE
AWS CloudFront deployment guide setup is more complicated than needed

### ISSUE THREAD

**Issue by marvin-j97** [withastro/docs#5193]
### 📚 Subject area/topic

S3 Deployment

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/deploy/aws/#s3-setup + all translations

## Current state

The guide says: `Unfortunately, CloudFront does not support multi-page sub-folder/index routing by default`

This is probably true, however it assumes the origin is a S3 bucket. Earlier in the guide, the user is guided through setting up S3 bucket _website hosting_. Using the S3 _website hosting endpoint_ as the origin, the [CloudFront Functions hack](https://docs.astro.build/en/guides/deploy/aws/#cloudfront-functions-setup) is not required because index.html etc are all resolved correctly. **This is also recommended by CloudFront**, see:

![Screenshot_from_2023-10-25_15-18-49](https://github.com/withastro/docs/assets/33938500/e3a2cc9d-c1d0-46ad-8e14-ca5200685b75)

## Proposal

- Keep the `S3 static website hosting` section as is.
- Remove `S3 with CloudFront > S3 setup`
- Remove `CloudFront Functions setup`
- Change `S3 with CloudFront > CloudFront setup` to use the S3 bucket **website hosting** origin

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

-

**Comment by sarah11918** [comment]
Hi! Thank you for pointing this out! If you'd like to make a PR with your suggestions to simplify this guide, we will take a look at it! Otherwise, we are in the process of migrating our docs site to Starlight and are not making large content changes ourselves right now, while we are focusing on a smooth transition.

So I will close this issue as it is not something we are looking to update right now, but would welcome a PR in the future!
