### ISSUE TITLE
Updating the `<script>` tag behavior to be more precise

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/docs#521]
Suggesting a rework around [this section](https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts) :

- more precisions than `// Processed! Bundled! ESM imports work, even to npm packages.`
- the lack of info about using npm package client side (maybe in a dedicated page)
- more info about what do the `type="module"` attribute
- describing that a tag loose it's default attributes (`hoist` and `type`) when given any
- more info about the behavior of `define:vars` when used on a script tag and it's limitation ([mentionned here](https://docs.astro.build/en/reference/directives-reference/#definevars), but need to search for it more than give this important information to the user)

- [x] I am willing to make a PR

Open to suggestion, as usual !

**Comment by aFuzzyBear** [comment]
I would second the notion of moving the scripts to a separate page.

**Comment by sarah11918** [comment]
>  As soon as you set type="module" or another attribute, you disable Astro’s hoisting and they are implicitly is:inline.

Ah, I'm just seeing @delucis 's comment here now, because I was mostly in the PR all day. But fortunately, I tagged him in the PR and asked him to fine-tune the wording of that very thing! 💅 

So, I'm going to close this as an Issue now, because we're very close to having that PR merged to improve the immedate handling of script on the astro-component page.

Writing a fuller, independent script page is on the stack, but a different task than this one. So, if @Chrissdroid needs an issue to keep track of for that, once the current PR is done, he can open another one.  ;)
