### ISSUE TITLE
⚠️ Issue react-dropzone library is not working

### ISSUE THREAD

**Issue by arifur-rahman-arif** [withastro/docs#5245]
`react-dropzone` library is not working with Astro when building the project

This is the error I'm getting
 error   Named export 'useDropzone' not found. The requested module 'react-dropzone' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'react-dropzone';
  const { useDropzone } = pkg;

![image](https://github.com/withastro/docs/assets/55947352/495e9f28-3ec6-430b-8897-ae7190d3a471)

**Astro version:** 3.4.0
**Node version:** 18.17.1

**Comment by delucis** [comment]
It looks like this is an issue with how `react-dropzone` is packaged: https://publint.dev/react-dropzone@14.2.3

One thing you can try is to set Vite’s `ssr.noExternal` configuration option in `astro.config.mjs`:

```js
// astro.config.mjs
import { defineConfig } from 'astro/config';

export default defineConfig({
  vite: {
    ssr: {
      noExternal: ['react-dropzone'],
    },
  },
});
```

Because this issue tracker is for Astro’s documentation website, I’ll close this issue. If you still have issues I’d recommend the `#support` channel in the [Astro Discord](https://astro.build/chat) or opening an issue with `react-dropzone` to encourage them to fix the packaging issues reported by Publint.

**Comment by arifur-rahman-arif** [comment]
If someone else is having this same problem. The workaround I've came up with is to copy the source `useDropzone` hook
in your own codebase along with installing the dependency the `react-dropzone` uses.
This way you can make you own custom react hook and you won't get any error while compiling

![image](https://github.com/withastro/docs/assets/55947352/d8dcf4b2-39d1-4ed1-b639-853bc5a9b272)
