### ISSUE TITLE
💡 Idea: add alternative way to include Astro.props on the client

### ISSUE THREAD

**Issue by endymion1818** [withastro/docs#5406]
https://docs.astro.build/en/guides/client-side-scripts/#pass-frontmatter-variables-to-scripts

This section can also be accomplished using the method on this page 

https://docs.astro.build/en/reference/directives-reference/#definevars 

However there is no reference to it here. It would be helpful to give people an easy reference to this alternative.

**Comment by delucis** [comment]
Thanks for the issue. The omission there was partially intentional because `define:vars` comes with quite a few drawbacks for script tags:
- prevents you from importing code into the script
- inlines the script every time the component is used, potentially running it more than once
- changes the script's scope from module to global

So in general I'd recommend against using `define:vars` for scripts for most cases.

**Comment by endymion1818** [comment]
Aha I see. I understand the point of view. I do still wish I'd known about it sooner for my particular use case. Happy with your decision either way.

**Comment by sarah11918** [comment]
Closing this, and message left in the corresponding closed PR! Thanks again, and hope to see you back in the docs repo soon!  :raised_hands:
