### ISSUE TITLE
Env variables should be in proj dir and not under src.

### ISSUE THREAD

**Issue by shriharip** [withastro/docs#5631]
### 📚 Subject area/topic

environment variables

### 📋 Page(s) affected (or suggested, for new content)

 https://docs.astro.build/en/guides/environment-variables/#intellisense-for-typescript

### 📋 General description or bullet points (if proposing new content)

To acheive Typescript intellisense, we need to create `env.d.ts` on the project directory and not inside `src` folder I think. I could not get it work as per the docs.

This line in the docs suggest doing it under `src` folder

To achieve this, you can create an env.d.ts in src/ and configure ImportMetaEnv like this: 

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

Sorry do not have a working repo

**Comment by mingjunlu** [comment]
Hi @shriharip,

Here's a [minimal example](https://stackblitz.com/edit/withastro-astro-te2w8i?file=src%2Fenv.d.ts&file=src%2Futils%2Fgreet.ts) created in StackBlitz. TypeScript IntelliSense seems to be fine (on StackBlitz and my local environment as well). Could you take a look and confirm if it's working?

![截圖 2023-12-06 上午10 28 46](https://github.com/withastro/docs/assets/40516784/78cd33f3-5100-4423-b5a1-598047d09318)

**Comment by lilnasy** [comment]
Thanks for opening an issue, @shriharip!

It is intentional that the file is located at `src/env.d.ts`. And if it isn't there, it will be created automatically next time you run any of astro cli's commands.

If intellisense is not working for you, it might help to discuss it in our discord: [astro.build/chat](https://astro.build/chat).
