### ISSUE TITLE
Internationalization Update(other docs)

### ISSUE THREAD

**Issue by helloimalastair** [withastro/docs#5728]
### 📚 Subject area/topic

Internationalization

### 📋 Page(s) affected (or suggested, for new content)

[i18n Recipe](https://docs.astro.build/en/recipes/i18n)
Maybe others

### 📋 General description or bullet points (if proposing new content)

With the announcement of the new Internationalization API, the section
> Astro doesn’t have built-in internationalization (i18n) support, but you can build your own i18n solution.

should maybe be updated to point to the [Internationalization API Guide](https://docs.astro.build/en/guides/internationalization/), or maybe the pages should be merged together.

**Comment by lilnasy** [comment]
You are right. I think it makes for it to mention the built-in feature. However, the recipe still has valuable information of its own, so it should stay.

We could immediately add something along the lines of "since this recipe was written, astro introduced a new feature...". Later (or instead), we could document the built-in feature for the parts it now helps with.

**Comment by VoxelMC** [comment]
How about something like this:

```diff
- Astro doesn’t have built-in internationalization (i18n) support, but you can build your own i18n solution. 
+ Since `v4.0`, Astro has built-in internationalization (i18n) support. However, if you prefer to do so, here is how you can build your own i18n solution.
```

Let me know what you think!

**Comment by lilnasy** [comment]
That seems great to me!
