### ISSUE TITLE
Left Sidebar Resets to Top After Page Refresh

### ISSUE THREAD

**Issue by yasnbouz** [withastro/docs#5771]
### 📝 Issue Description

Every time the page is refreshed, the scroll position in the left sidebar is lost and automatically resets to the top. This behavior occurs consistently upon every page refresh.

### 📋 On which page(s) it occurs

Occurs on all pages that have left sidebar

### 🤔 Expected Behavior

Implementing a feature to preserve the scroll position in the browser storage could resolve this issue.

[Expected Behavior](https://github.com/withastro/docs/assets/45861586/468fdf88-6ae5-457f-8b88-d655810025d1)

### 👀 Current Behavior

[Current Behavior](https://github.com/withastro/docs/assets/45861586/12e1e45e-1e58-44c7-a433-aa1cb9659fc2)

### 🖥️ Browser

Edge

**Comment by sarah11918** [comment]
Thank you for raising this issue! As you can see, we have already opened a PR that would fix this issue in Astro Docs. However, we are also discussing whether this is something we want to address in Starlight itself, which would then apply to Astro Docs, and also be built-in for everyone!

So, I will close this issue here as we might in fact handle this in another repo, and fixing there would not automatically close this issue. But, we are working on this! Just figuring out the best place to make the fix! Hope you have a wonderful new year, and thank you again for pointing this out!

**Comment by yasnbouz** [comment]
Thanks for the update on the issue. It's good to know a fix is underway. Looking forward to it. The idea of addressing this in Starlight sounds promising as it would benefit everyone. I appreciate your team's effort in figuring out the best place to make the fix. Wishing you a wonderful new year too! 🎉
