### ISSUE TITLE
Issue with Astro Gatsby Migration Guide

### ISSUE THREAD

**Issue by LandonSchropp** [withastro/docs#5945]
### 📚 Subject area/topic

Migration guide

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/migrate-to-astro/from-gatsby/

(I'm not sure if this affects other pages)

### 📋 Description of content that is out-of-date or incorrect

The guide advocates for launching the Astro wizard with the following command:

``` shell
yarn create astro@latest
```

However, this produces an error for me with the latest `yarn`:

```
yarn create v1.22.21
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-astro@4.6.0" with binaries:
      - create-astro
/bin/sh: /usr/local/bin/create-astro@latest: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-astro@latest
...
```

Running `yarn create astro` works fine.

**Comment by ElianCodes** [comment]
Hey there! This issue doesn't seem to happen on my part. Are you sure this isn't/wasn't a local problem?

<img width="708" alt="Screenshot 2023-12-26 at 14 55 48" src="https://github.com/withastro/docs/assets/15145918/5cb53f15-a9a8-4427-9fb4-7acd5ed892ca">

**Comment by sarah11918** [comment]
Hi @LandonSchropp ! Thanks for mentioning this, but this isn't specific to the Gatsby guide. These are our basic installation instructions that we sometimes do/sometimes don't specify `@latest`. These instructions are correct, and if they're not working, that's either a bug or something happening in your local setup!

So, I'm going to close this as it's not a documentation issue, but we would love it if you continue to be unable to run this command to please reach out in a support thread on Discord where someone can help you troubleshoot this! https://astro.build/chat If it turns out we have a bug, or an issue pointing to our latest branch, then we for sure want to know about this!

**Comment by LandonSchropp** [comment]
My bad—it must be a local issue. Thanks!
