### ISSUE TITLE
Add Information on Mixing SolidJS and React

### ISSUE THREAD

**Issue by gsi-kevincarrera** [withastro/docs#5995]
In a previous issue titled ‘Strange behavior mixing SolidJS and React’, an unusual behavior when mixing SolidJS and React was identified and resolved. One of the contributors suggested that this information would be useful to add to the documentation.

https://github.com/withastro/astro/issues/9523

**Comment by gsi-kevincarrera** [comment]
If someone could give me a guidance to contribute on this, would be great

**Comment by sarah11918** [comment]
Hi @gsi-kevincarrera ! You can find lots of guidance on contributing at https://contributing.docs.astro.build and we really hope you will!

You can take a read through our first-time contributing, and this is probably simple enough to do by "editing a single page". It would be wonderful if you would contribute this for us.

**Comment by gsi-kevincarrera** [comment]
Thanks! I'll get on it

**Comment by sarah11918** [comment]
@gsi-kevincarrera Please let me know if you need any further guidance! I would love to start the new year with zero issues... ;)

**Comment by gsi-kevincarrera** [comment]
Yes, I'm feeling kinda lost about where to put the information :(. I will love to help

**Comment by sarah11918** [comment]
@gsi-kevincarrera No problem! From @bluwy 's comment, it looks like you can add to line 130 in this file:

https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/integrations-guide/solid-js.mdx

So, I would:
- go to the above link
- in the upper right, there's a pencil icon to "edit this file"
- go to line 130 which currently says `include: ['**/solid/*'],` and add to it so that it now reads `include: ['**/solid/*', '**/node_modules/@suid/material/**],'
-  click Commit changes. This will automatically create a fork of the docs in your GitHub account with the changes.
- once you have committed your edits to your fork, follow the prompts to create a pull request.

You can also read an annotated blog post with screenshots [demonstrating the process of editing the docs this way](https://www.rainsberger.ca/posts/contribute-open-source-docs-edit-page-on-github/).

Try this, and let me know if you have any issues!

**Comment by gsi-kevincarrera** [comment]
Thank you so much! You so great :)

**Comment by gsi-kevincarrera** [comment]
Done, thanks for the guidance. I will do it better the next time
