### ISSUE TITLE
i18n(pt-BR): Update translation for `reference/configuration-reference`

### ISSUE THREAD

**Issue by vitorxfs** [withastro/docs#6177]
### 📚 Subject area/topic

Configuration Reference translation to pt-BR

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/pt-br/reference/configuration-reference/

### 📋 Description of content that is out-of-date or incorrect

The translation to pt-BR in `/reference/configuration-reference/` is outdated, with the following missing sections:
- `Prefetch Options`
- `Dev Toolbar Options`
- `i18n`

There are also outdated content in other sections of the page to be fixed.

**Comment by sarah11918** [comment]
Hi! We keep track of our translation status at https://i18n.docs.astro.build/ so we do always know what needs updating. No need to file an issue for this!

Unfortunately, due to the way our documentation process works, pages are written/updated first in English and then our volunteer translators update their language pages as they have time. It is unlikely that other languages are perfectly translated, but we do have a system in place already for tracking this so I am closing this issue.

We are always happy to receive translations to help us update the site! If you are interested, you can find out more here: https://contribute.docs.astro.build/guides/i18n/
