### ISSUE TITLE
Language selector can't go back to English 404 page

### ISSUE THREAD

**Issue by Fryuni** [withastro/docs#6182]
### 📝 Issue Description

On any unknown URL, like https://docs.astro.build/foo/, the language selector doesn't work when trying to go back to English.

### 📋 On which page(s) it occurs

Any 404 page

### 🤔 Expected Behavior

Selecting English on a translated 404 page should go to the English 404 page

### 👀 Current Behavior

Going from English to any other language and switching between them works, but not going back to the default language.

### 🖥️ Browser

Chrome 120.0.6099.129

### 📄 Additional Information

This bug doesn't happen on Starlight. If you go to https://starlight.astro.build/foo/, you can switch back and forth between any language including English.

**Comment by Fryuni** [comment]
Can someone tag the lowest of all low priorities labels for this pls. I almost didn't open the issue because it is working for every page and every transition except the 404 page switching to English. As minor a bug as it can get.

**Comment by sarah11918** [comment]
I've updated the title here because when we migrated to Vercel, we had to do some customization to even get our 404 page to work. So, I'm quite sure this is less of a "language selector" issue and more a 404 page issue. It might not be possible to improve the behaviour, but @delucis would know!

**Comment by Fryuni** [comment]
It works on Starlight's own that is also deployed to Vercel and uses the same URL patterns for the locales. So it doesn't seem like a platform limitation.

Maybe something that differs on the overrides here?

**Comment by delucis** [comment]
Yeah, the docs version does something a bit different for multilingual 404s to work around Vercel’s lack of support for multiple 404 pages. Starlight does this with some “fun” config in `vercel.json` to support actually serving each language’s `404.html` but that approach was not viable in docs with so many redirects needed, so we just always serve the English page and switch out the main content.

The issue is that the language picker [listens for a change event](https://github.com/withastro/starlight/blob/8994d007266e0bd8e6116b306ccd9e24c9710411/packages/starlight/components/LanguageSelect.astro#L41), but in this case nothing is _changing_. Could perhaps be addressed upstream by just running the redirect logic any time an option is chosen even if it is currently selected? I honestly don’t even know if that’s reliably possible (i.e. the distinction between a) user opens the picker then clicks away and b) user opens the picker then clicks the current item).

Or alternatively, the docs 404 could maybe just do this:
```js
document.querySelector('starlight-lang-select select').value = `/${lang}/404/`;
```

That could be the simplest fix given this is a pretty rare use case.

**Comment by mingjunlu** [comment]
Hey friends,

I came up with a possible solution to this issue:

1. Add a `<script>` to docs 404 page
2. Check if current language in URL matches any option in the language selector
3. If there's a match, apply the option's value to the language selector

Expected results:

- Allow the user to switch to English 404 page
- Resolve inconsistent displayed languages (main content of 404 vs language selector on the top right)

Here's a [draft PR](https://github.com/withastro/docs/pull/6763). Would love to hear your feedback 🙂
