### ISSUE TITLE
Image Service API Search Result

### ISSUE THREAD

**Issue by Jothsa** [withastro/docs#6314]
### 📝 Issue Description

When searching for "Image Service API" the [Image Service API](https://docs.astro.build/en/reference/image-service-reference/) page did not show up at all. I was unable to find this page via the search function at all.

### 📋 On which page(s) it occurs

sitewide

### 🤔 Expected Behavior

I expected the page title "Image Service API" to rank highly when searching for "Image Service API"

### 👀 Current Behavior

But instead, the expected page does not show up at all in search results

### 🖥️ Browser

Safari 17.2

**Comment by sarah11918** [comment]
This *is* weird! I know some pages have selective ranking so maybe there's something weird and this page is not actually being indexed by Algolia.

Thank you so much for reporting this! cc @delucis

**Comment by sarah11918** [comment]
Hi @Jothsa - we reindexed Algolia (basically rebuilt the search results) and in our testing on our end, we are now seeing the search result show up. It might have just been a fluke in the last run when Algolia indexed our site.

So, I'm going to close this issue because we are now seeing the proper hit come up (first result!) but if you discover anything in future, please do come back and reopen, or file another issue. Thank you again for reporting!  🚀

**Comment by Jothsa** [comment]
Thanks!
