### ISSUE TITLE
Remark plugin using TypeScript

### ISSUE THREAD

**Issue by dhruvkb** [withastro/docs#6501]
### 📚 Subject area/topic

Recipes

### 📋 Suggested page

We have a recipe for a Remark plugin that would add the modified time to the Astro frontmatter.

https://github.com/withastro/docs/blob/e20c47fa0726207051b00aa26269ff2066420027/src/content/docs/en/recipes/modified-time.mdx

This recipe uses JavaScript and does not contain types.

### 📋 General description or bullet points (if proposing new content)

A plugin written in TypeScript would be help TS users.

**Comment by sarah11918** [comment]
Thank you for mentioning this! We do have plans to add more TypeScript examples throughout the docs. Right now, we have focused on all examples using JavaScript only so that they are most accessible to all our users, even the ones not using TypeScript.

We do also want to show TypeScript alternatives for many pages, and we appreciate hearing that this would be valuable for you! I am closing this as an issue, since we will be planning to review our documentation to better support TypeScript, and thank you for letting us know your preference!
