### ISSUE TITLE
Missing type safety when passing frontmatter to layout of content collection

### ISSUE THREAD

**Issue by kareemmahlees** [withastro/docs#6615]
### 📚 Subject area/topic

Content Collections

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/tutorial/4-layouts/2/

### 📋 Description of content that is out-of-date or incorrect

While passing the frontamatter data to the MarkdownPostLayout, it doesn't say how to make it typesafe and the frontmatter is typed as `any`
```md
---
const { frontmatter } = Astro.props;
//          ^? any
---
<h1>{frontmatter.title}</h1>
<p>Written by {frontmatter.author}</p>
<slot />
```
The solution is pretty simple actually: 
```md
---
+ type Props {
+ frontmatter: CollectionEntry<"collection_name_here">["data"];
+}

const { frontmatter } = Astro.props;
---
<h1>{frontmatter.title}</h1>
<p>Written by {frontmatter.author}</p>
<slot />
```

**Comment by at-the-vr** [comment]
[Setup Wizard](https://docs.astro.build/en/tutorial/1-setup/2/#launch-the-astro-setup-wizard) went NO for using typescript for the tutorial. What that means is this typescript error will not occur (I didn't saw this occurring on Stackblitz as well)

**Comment by kareemmahlees** [comment]
> [Setup Wizard](https://docs.astro.build/en/tutorial/1-setup/2/#launch-the-astro-setup-wizard) went NO for using typescript for the tutorial. What that means is this typescript error will not occur (I didn't saw this occurring on Stackblitz as well)

Yes, but that is the problem, there are no errors because the frontmatter is typed as `any`, if I were to use a frontmatter property that doesn't exist it wouldn't error until it renders the page.

**Comment by sarah11918** [comment]
Hi @kareemmahlees ! Yes, as Atharva said, this page intentionally does *not* include any typing and does not use a TypeScript setting that displays browser errors. If one has followed the instructions, and set the appropriate TypeScript setting, then there will be no error.

We are looking at adding more TypeScript examples throughout the docs, since of course many people *are* using one of our stricter TypeScript settings and relying on this typesafety. But for this exact example, it is not appropriate to add it to this guide because this is a tutorial meant to be accessible even those who are not very familiar with JavaScript, and so we intentionally do not assume any TypeScript knowledge. This very beginner tutorial is only to show the basics of how Astro works, and we don't necessarily want to add TypeScript at this point. We may consider updating / including a TypeScript version in the future!
