### ISSUE TITLE
Missing description of different results of `paginate()` when using rest parameter in file-based routing

### ISSUE THREAD

**Issue by izmttk** [withastro/docs#6984]
### 📚 Subject area/topic

pagination, routing

### 📋 Suggested page

https://docs.astro.build/en/guides/routing/#pagination

### 📋 General description or bullet points (if proposing new content)

I found an undocumented behavior of `paginate()` when rest parameter was used in file-based routing.
For instance, if we have the following code in an astro file with different filenames:

```js
export async function getStaticPaths({ paginate }) {
  // ... get articles
  return paginate(articles, { pageSize: 10 });
}
```

1. `astronauts/[page].astro`
   
   The first item in result will be:
   
   ```js
   {
     params: { page: '1' },
     props: {
       // ...
     }
   }
   ```
   This will generate `/astronauts/1`, `/astronauts/2`, ...

2. `astronauts/[...page].astro`
   
   The first item in result, which is related to page 1, will be
   
   ```js
   {
     params: { page: undefined },
     props: {
       // ...
     }
   }
   ```
   This will generate `/astronauts`, `/astronauts/2`, ...

The main difference is whether first page number is included in generatrd paths.
Related code can be referred to: 
https://github.com/withastro/astro/blob/7c5fcd2fa817472f480bbfbbc11b9ed71a7210ab/packages/astro/src/core/render/paginate.ts#L23-L28

If docs already contain the above content, pls let me know, thanks.

**Comment by Fryuni** [comment]
Guides are not necessarily comprehensive regarding everything possible with a particular feature. Some properties and their use cases are mentioned only in the extensive reference since they are not relevant to explain how the _concept_ of pagination is achieved in Astro.

The [reference for the `paginate` function](https://docs.astro.build/en/reference/api-reference/#paginate) has the following section:

> `paginate()` assumes a file name of `[page].astro` or `[...page].astro`. The `page` param becomes the page number in your URL:
>
> - `/posts/[page].astro` would generate the URLs `/posts/1`, `/posts/2`, `/posts/3`, etc.
> - `/posts/[...page].astro` would generate the URLs `/posts`, `/posts/2`, `/posts/3`, etc.

Do you think this is something that should be mentioned in the guide?

**Comment by izmttk** [comment]
yes, it seems that I missed this part, thank u.
