### ISSUE TITLE
Suggestion to improve the docs for the Code component

### ISSUE THREAD

**Issue by ttmc** [withastro/docs#7078]
[The docs about the Code component](https://docs.astro.build/en/reference/api-reference/#code-) give examples of how you could use it in an Astro file (.astro):

```astro
---
import { Code } from 'astro:components';
---
<!-- Syntax highlight some JavaScript code. -->
<Code code={`const foo = 'bar';`} lang="js" />
<!-- Optional: Customize your theme. -->
<Code code={`const foo = 'bar';`} lang="js" theme="dark-plus" />
<!-- Optional: Enable word wrapping. -->
<Code code={`const foo = 'bar';`} lang="js" wrap />
<!-- Optional: Output inline code. -->
<p>
  <Code code={`const foo = 'bar';`} lang="js" inline />
  will be rendered inline.
</p>
```

I found that one must be very careful to inspect their code and replace `\n` with `\\n`, otherwise it will be converted to an actual newline in the rendered output. Similarly, `\t` must be replaced with `\\t`, and so on. Backticks-in-code must also be escaped. Doing that is tricky and error-prone. Ideally, one could just copy some raw code from their IDE/text editor straight into their .astro file, somewhere, and be done.

Good news: it's possible, and here's how... just append `String.raw` before the first backtick. That way everything inside the backticks will be interepreted as a raw string.

The above example code, in the docs, would become:

```astro
---
import { Code } from 'astro:components';
---
<!-- Syntax highlight some JavaScript code. -->
<Code code={String.raw`const foo = 'bar';`} lang="js" />
<!-- Optional: Customize your theme. -->
<Code code={String.raw`const foo = 'bar';`} lang="js" theme="dark-plus" />
<!-- Optional: Enable word wrapping. -->
<Code code={String.raw`const foo = 'bar';`} lang="js" wrap />
<!-- Optional: Output inline code. -->
<p>
  <Code code={String.raw`const foo = 'bar';`} lang="js" inline />
  will be rendered inline.
</p>
```

**Comment by sarah11918** [comment]
Hi @ttmc ! Revisiting this one as we are going to update our `<Code />` documentation tomorrow with our minor release that will add a new prop to it! (So sorry we are very behind on some of our longstanding issues here. Thank you for your patience!)

Instead of updating each sample, (which is meant to illustrate the props of the code component, and further adding to them distracts from that), I think it could be great to add a note directly under the existing paragraph something like...


> To make escaping characters easier (e.g. backticks, new lines etc.), consider defining your code as a variable, or prepending inline `code` strings with [`Raw.string`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw):

```
---
import { Code } from 'astro:components';
const code = `const foo = 'bar';`
---
<Code code={code} lang="js" />
<Code code={String.raw`const foo = 'bar';`} lang="js" />
```

(I *believe* using a variable avoids this problem, too. If I'm wrong, we cut that part out.)

If you would like to make a PR to update the docs in this way, I would happily accept one!

**Comment by sarah11918** [comment]
Closing this as not something to document at this time.
