### ISSUE TITLE
Clarify how to add images to RSS

### ISSUE THREAD

**Issue by tommyp** [withastro/docs#7099]
### 📚 Subject area/topic

RSS

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/rss/

### 📋 Description of content that is out-of-date or incorrect

Following the guide for adding an RSS feed, you'll be left with an RSS feed with no images.

Explaining how to add this with `sanitize-html` would be good. 

I've forked and added this [here](https://github.com/tommyp/docs/commit/32ed22fa5c8dac1c2a8a921dfb4238a6edc9ed2a), until I read that I should open an issue for something more than a typo.

Happy to open a PR with my fork too.

**Comment by tommyp** [comment]
@at-the-vr Is it ok to open a PR for my fork?

**Comment by at-the-vr** [comment]
I gotta ask if you could wait for approval from maintainers 🙏

**Comment by sarah11918** [comment]
Hi @tommyp , this looks like a great idea to add to the RSS content! Thank you for suggesting it!

Thank you for also waiting for the discussion here, and I do have thoughts...

Since we try to keep things concise and simple for everyone, what would you think about working this into the main example itself? So, no second code sample, but add everything required to the original code sample?

So, assume someone *did* want to include images. What all is required to add to that snippet, and what does the whole thing look like?

The line could be adjusted to something like:

> When using content collections, render the post `body` using a standard Markdown parser like [`markdown-it`](https://github.com/markdown-it/markdown-it) and sanitize the result, including any extra tags (e.g. `<img>`) needed to render your content:

Would be happy to receive a PR along those lines, and we can work out the fine details in the PR itself!  :raised_hands:

**Comment by SatanshuMishra** [comment]
I am happy to take a look at implementing this. Since @tommyp already has a fork that does some of the work, if he gets a PR in will let him take it :)!

**Comment by tommyp** [comment]
@sarah11918 Thanks for the suggestion and the vote of confidence @SatanshuMishra! I've opened the PR. Glad I could make a contribution to such an awesome project.
