### ISSUE TITLE
Incomplete or unclear guide for custom MDX components

### ISSUE THREAD

**Issue by aureliendossantos** [withastro/docs#7208]
### 📚 Subject area/topic

MDX custom components

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/markdown-content/

### 📋 Description of content that is out-of-date or incorrect

I’ve been trying to figure out how to use custom MDX components, and I think a few points in the docs need clarification, especially as a user of content collections:

1. [There is a simple example](https://docs.astro.build/en/guides/markdown-content/#assigning-custom-components-to-html-elements) of how to make a custom `> blockquote` using `<slot />`. However, neither the Astro docs nor the linked MDX page explain how to write the custom component for a more complex syntax like `[title](http://link)`.

2. [This example](https://docs.astro.build/en/guides/markdown-content/#custom-components-with-imported-mdx) seems useful if you directly import a `.mdx` file, but is confusing if you use a content collection, because the `components` variable doesn’t exist, so you don’t know if you still have to import and pass back your custom components, as said in the “Note”.

3. The same example shows that you can replace a set of keywords `h1`, `a`, etc. with a custom component. However, it wasn’t clear to me that you can simply pass a component like this: `<Content components={{ MyComponent }} />`. I just randomly tried it and it worked. I think it should be more clear because it’s precisely what I was looking for: I didn't need to replace a keyword like `h1`, but my own custom component depending on the page rendering the `<Content />`, ie by doing `<Content components={{ MyComponent: AlternativeComponent }} />`.

I hope this feedback can be useful!

**Comment by sarah11918** [comment]
Hi! We are trying to wrangle some of our older issues and I'm sorry it's taken a while to get to this one!

You may have noticed that we have reorganized our MDX content since this issue was filed, so the content in question is now in our MDX guide directly.

I'm wondering, to point #3, if you would find something like this addition to the code example helpful, to show not just a renaming of existing elements but replacing of components:

```
<Content components={{...components, h1: Heading,  MyComponent: AlternativeComponent }} />
```

If so, that content is now located on this page in docs: https://docs.astro.build/en/guides/integrations-guide/mdx/#custom-components-with-imported-mdx and we would consider a PR to this page with some kind of change like that if you think it would put the connection in people's minds while reading!

**Comment by sarah11918** [comment]
We discussed this on Talking and Doc'ing and decided this was a bit more of a niche use case than we want to show in docs, and decided to keep the example short showing the HTML element replacement with custom components.
