### ISSUE TITLE
Missing: Rendering content to HTML for `getCollection`

### ISSUE THREAD

**Issue by MiloParigi** [withastro/docs#7245]
### 📚 Subject area/topic

Content collection - Rendering content to html

### 📋 Suggested page

https://docs.astro.build/en/guides/content-collections/#rendering-content-to-html

### 📋 General description or bullet points (if proposing new content)

The current documentation show us how to generate the content when using the `getEntry` method for one entry only:

![Screenshot 2024-03-08 at 10 52 13](https://github.com/withastro/docs/assets/20594983/f5f3e008-6a6d-485b-ad3c-6c57c7af4944)

In my current use case, I have a collection of entries that I want to be rendered on one page. After fiddling for a few hours, here is a similar example to the one provided for one entry. but for multiple entries:

```astro
---
import { getCollection } from 'astro:content';
const blogEntries = await getCollection('blog');
const renderedBlogEntries = await Promise.all(blogEntries.map(async (blogEntry) => {
    const { Content, headings } = await blogEntry.render();
    return { ...blogEntry, Content, headings };
}));
---
<div>
  {blogEntries.map(blogEntry => (
      <h1>{blogEntry.data.title}<h1>
      <blogEntry.Content />
    ))}
</div>
```

I'll make a StackBlitz example when I have the time but I wanted to share the solution first, so that anybody stuck on this problem can at least fix it if they find this issue.

**Comment by sarah11918** [comment]
Yes, there are several ways to achieve this, including looking at the source in our own [blog template](https://github.com/withastro/astro/blob/latest/examples/blog/src/pages/blog/index.astro) or our instructions to [convert to `getCollections()` instead of `Astro.glob()`](https://docs.astro.build/en/tutorials/add-content-collections/#replace-astroglob-with-getcollection). An example of accessing multiple entries and displaying them via a `map` is also shown here in the [Accessing referenced data](https://docs.astro.build/en/guides/content-collections/#accessing-referenced-data) section of the page. I'm glad you figured something out that worked for you! 🙌
