### ISSUE TITLE
Integrations with a broken link (a typo in the url)

### ISSUE THREAD

**Issue by f33w** [withastro/docs#7389]
### 📚 Subject area/topic

integrations page

### 📋 Page(s) affected (or suggested, for new content)

https://astro.build/integrations/?categories%5B%5D=recent

### 📋 Description of content that is out-of-date or incorrect

1. The integration @advanced-astro/toast has a broken link due to a typo (advenced instead of advanced) in the url. Correct url will be https://github.com/advanced-astro/toast

2. The integration @m4rrc0/astro-fetch-ahead have a broken link https://github.com/m4rrc0/poko-notion/astro-integrations/astro-fetch-ahead that should be pointing somewhere here https://github.com/m4rrc0/poko-notion

**Comment by ctrimm** [comment]
Thank you for filing this issue @f33w.

Based on my understanding of how the astro docs are generated, the fix for this issue should be in the [astro.build repository](https://github.com/withastro/astro.build).

You can see that I just opened a [Pull Request in that repository](https://github.com/withastro/astro.build/pull/1027). Once an Astro team member merges the changes, we can safely close out this issue.

**Comment by f33w** [comment]
@ctrimm thanks for providing a link to the repo, I was looking for it to fix it myself, still new to this stuff. Commited changes

**Comment by ctrimm** [comment]
No worries @f33w!

Your issue inspired me to look for a fix and explore the docs. Feel free to close this issue - looks like I'm waiting for approval from an [Astro core team-member to approve a test deploy](https://github.com/withastro/astro.build/pull/1027#issuecomment-1999313543).
