### ISSUE TITLE
⚠️ Issue // getting error at buildtime while using the sitemap integration.

### ISSUE THREAD

**Issue by DarkidOP** [withastro/docs#7450]
![image](https://github.com/withastro/docs/assets/60326315/048ec924-e7e8-4bf7-abe6-6665b71fa43f)

**Comment by mingjunlu** [comment]
Hi @DarkidOP,

Could you provide a minimal example for reproducing this error? Either [StackBlitz](https://astro.new/basics?on=stackblitz) or GitHub repo is fine 🙂

**Comment by sarah11918** [comment]
I'm sorry the sitemap integration is giving you trouble, @DarkidOP ! Just a quick note that this repo is for errors in the documentation itself, for example if we have typos or poor instructions. If it turns out this is a bug in Astro itself, then we will move this to the Astro repo. And if this becomes a support question, helping you troubleshoot your own code, then that would usually be handled in Discord and not filed as a problem with our docs.

So, happy to keep this open and let you provide the reproduction, but your issue will only stay here if it's something wrong with our instructions in the docs. So, do keep an eye out for that because *that*'s really what we can help with here! Otherwise, we're happy to get you to the right place for proper assistance!

**Comment by DarkidOP** [comment]
Hello @mingjunlu,
sorry for the late response. it would be easier for me to just provide you with the repo link, but its a private repo currently. would it be possible for you to accept an invitation to the repo and then check it out?

and it's most likely a bug since I didn't really change much in my code and I even tried rolling back to the last working git version of the codebase. in that case, where should I submit the issue? @sarah11918 

and as for recreation, you would just need the current code in the main branch of the repo, and have the code below in the "astro.config.mjs" file. @mingjunlu 

```import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";

import sanity from "astro-sanity";

// https://astro.build/config
export default defineConfig({
  site: "https://www.zeneticesports.com",
  integrations: [
    sitemap(),
    sanity({
      projectId: "shzuwr9q",
      dataset: "production",
      apiVersion: "v2021-03-25",
      useCdn: false,
    }),
  ],
});
```

**Comment by DarkidOP** [comment]
Hello @mingjunlu,
sorry for the late response. it would be easier for me to just provide you with the repo link, but its a private repo currently. would it be possible for you to accept an invitation to the repo and then check it out?

and it's most likely a bug since I didn't really change much in my code and I even tried rolling back to the last working git version of the codebase. in that case, where should I submit the issue? @sarah11918 

and as for recreation, you would just need the current code in the main branch of the repo, and have the code below in the "astro.config.mjs" file. @mingjunlu 

```import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";

import sanity from "astro-sanity";

// https://astro.build/config
export default defineConfig({
  site: "https://www.zeneticesports.com",
  integrations: [
    sitemap(),
    sanity({
      projectId: "",
      dataset: "production",
      apiVersion: "v2021-03-25",
      useCdn: false,
    }),
  ],
});
```

**Comment by sarah11918** [comment]
@DarkidOP I'll transfer this issue to the main Astro repo as a bug report!
