### ISSUE TITLE
Getting validation error "Property view-transition-name doesn't exist" with ViewTransitions

### ISSUE THREAD

**Issue by timokleemann** [withastro/docs#7807]
I am getting a bunch of errors like these when trying to validate the HTML generated by Astro:

`Error: CSS: view-transition-name: Property view-transition-name doesn't exist.`

[This is my page](https://www.designbits.de/projects) (A classic use case for Astro's View Transitions by the way.)

And [this is the error page](https://validator.w3.org/nu/?doc=https://www.designbits.de/projects) that [W3C Validator](https://validator.w3.org) is giving me.

What am I missing here?

**Comment by TheOtterlord** [comment]
Sorry for the wait. I hadn't seen this issue when I last triaged :sweat_smile: 

It looks like the page you linked passes the validator. My guess is the validator hadn't been updated to include newer features, but has been since. I'll close the issue as there's no further action here, but feel free to respond here if I've missed something, or ping me in our [Discord](https://astro.build/chat) support.
