### ISSUE TITLE
How to use js cdn with astro

### ISSUE THREAD

**Issue by Parsepec** [withastro/docs#790]
Trying to use a UI library "UIKit" in a project the css CDN works fine but the JS CDN doesn't seem to work
![UIKIT](https://user-images.githubusercontent.com/47125163/174988722-d884d308-60ea-4f8b-929c-c02475ddb9aa.png)

**Comment by shaunchander** [comment]
> Trying to use a UI library "UIKit" in a project the css CDN works fine but the JS CDN doesn't seem to work

How are you loading your JS in? Can you post a snippet?

**Comment by sarah11918** [comment]
Hi @Parsepec ! I am going to close this issue because these Issues are for problems with the documentation site iteslf. Unfortunately, we are not able to help with Astro troubleshooting here, and your question won't get the proper attention.

To receive help with Astro, please visit our Discord and ask in the support-thread channel at https://astro.build/chat There will be people who will be happy to help you there! That is where our support takes place!
