### ISSUE TITLE
Give guidance on adblockers

### ISSUE THREAD

**Issue by matthewp** [withastro/docs#815]
From https://github.com/withastro/astro/pull/3658

We want to re-enable readable names in our JS output in the build. However, if you have a file like `ad.js` that might create a bundle that will be blocked by an ad-blocker in the browser. You can control the output file names with:

```js
export default {
  vite: {
    build: {
      rollupOptions: {
         entryFileNames: 'entry.[hash].js',
         chunkFileNames: 'chunks/chunk.[hash].js',
         assetFileNames: 'assets/asset.[hash][extname]',
      }
    }
  }
}
```

We should document this... somewhere. Not sure the best place.

**Comment by FredKSchott** [comment]
Yea, the weird edge-case that we hit originally was that ad blockers were blocking the JS generated for this page: https://partytown.builder.io/google-tag-manager since Astro generated a file called `google-tag-manager.js` based on the page URL.

I think this is such a rare edge case, maybe just having this GitHub issue (and the one in our main repo) is enough. If your site hits this, you'll search for it, and then find this issue...

Otherwise, we could do a silly `console.warn` inside of Astro itself when its generating files, that warns on a few known file names (`ad.js`, etc).

But fwiw, I don't think that this edge case needs any docs dedicated to it, given how rare it is expected to be.

**Comment by delucis** [comment]
Sounds fair. We _could_ just document the filename config option? (Briefly with a link to Vite for full docs.) That way when the search comes for "filename config" or whatever there's something instead of nothing.

**Comment by sarah11918** [comment]
Closing as it seems this was decided to be an edge case not for documenting.
