### ISSUE TITLE
Give us feedback form Appearance is not in line with Astro Doc Styling

### ISSUE THREAD

**Issue by SatanshuMishra** [withastro/docs#8194]
### 📝 Issue Description

The `Give us feedback` form seems to be inconsistent with the general styling of the Astro docs. More specifically, the Submit button seems to be missing bordering styling and the Privacy Policy link seems to be the default link tag with default text styling.

### 📋 On which page(s) it occurs

This is present on all pages since the form is accessed via the RightSideBar.

### 🤔 Expected Behavior

Change border styling of the submit button to have a transparent background, grey border, and grey text. The Privacy Policy link should have text decoration removed and be centered on the modal with simple white text (and possibly an icon to the left).

### 👀 Current Behavior

Instead of the above, the submit button has the default HTML border styling and text-decoration. The Privacy Policy button also has the default HTML text-decoration.

### 🖥️ Browser

Arc Version 1.41.0, Chrome Version 124.0.6367.119

### 📄 Additional Information

Screenshot of the module in question is attached below:
![image](https://github.com/withastro/docs/assets/63601536/8a3f7746-69de-44e5-9c54-c745438b3aa0)

**Comment by delucis** [comment]
Thanks for flagging @SatanshuMishra!

Here is our reference design:

<img width="1063" alt="image" src="https://github.com/withastro/docs/assets/357379/79dfe185-5ee8-46fb-b9d9-10ffe114af44">

And a link to the Figma design: https://www.figma.com/file/GrDkcguAR7tSWPFuLVDixq/Theme---Starlight-Docs?type=design&node-id=454-34754&mode=design&t=FMXLtlWkDCNniwh2-4

We added the Privacy Policy link later, so it’s not shown in the design. I think the style for that is OK though — it matches other links on the site.

The submit button probably needs a `border: 0` though and if we’re really picky, the issue/idea/other buttons outline should overlap with their container border rather than being inside it.

**Comment by sarah11918** [comment]
Adding some help wanted labels here in case anyone wants to help style the submit button closer to our original Figma design!
 
 As Chris said, there isn't a need to change our privacy policy link, which should continue to just have default link styling to match the rest of the page. But the submit button does look a little gloomy right now! Anyone up for giving it some love?
