### ISSUE TITLE
RTL Docs `Inline Code Snippet` need to be always LTR. 

### ISSUE THREAD

**Issue by X7md** [withastro/docs#8209]
### 📝 Issue Description

This `</ slot>`:

![image](https://github.com/withastro/docs/assets/54203033/eacaa3f3-e8b2-4ff9-8023-21ab0f044826)

Should looks like this `<slot />`: 

![image](https://github.com/withastro/docs/assets/54203033/0fbfcdab-32e6-4440-8685-9a88b85bb574)

### 📋 On which page(s) it occurs

https://docs.astro.build/ar/basics/astro-components/

and others...

### 🤔 Expected Behavior

force inline code to be LTR.

### 👀 Current Behavior

In Arabic Docs Inline Code Snippet shows as RTL and that break the original code, symbols usually looks reverses which is wrong.  

### 🖥️ Browser

Chrome 124.0.6367.119 (Official Build) (64-bit) (cohort: Stable)

**Comment by sarah11918** [comment]
Thanks for reporting this! I will make sure @delucis and @TheOtterlord have this on their radar to look into!

**Comment by TheOtterlord** [comment]
Hi @X7md, are you still seeing the issue? I'm unable to replicate this either in Chrome / Firefox. It could be that an update to Starlight fixed this, but I don't see anything specific.

**Comment by X7md** [comment]
> Hi @X7md, are you still seeing the issue? I'm unable to replicate this either in Chrome / Firefox. It could be that an update to Starlight fixed this, but I don't see anything specific.

You are right, there is some changes form last time I checked... someone add `dir` attribute with auto in the inline `<code>` tags... but still replicate in some context like lists `<ul>`, `<ol>`... and as far as I know this because some limitations on the "bi-directional algorithm" on text rendering.

for me I prefer to using something like this:

https://github.com/X7md/x7md.github.io/blob/b649d3585d345e6f2835344a9b13fdc2b6553575/src/layouts/Layout.astro#L107-L116


![IMG_2159](https://github.com/withastro/docs/assets/54203033/1422ea18-f664-4ef1-816a-199d348a8e98)

![IMG_2160](https://github.com/withastro/docs/assets/54203033/d7f9cdcf-d095-453f-ba17-f017087b760a)

**Comment by delucis** [comment]
Thanks for sharing @X7md! I think the list formatting issue you screenshotted there is actually a problem with the source file, which includes the `.` in the wrong place unless I’m mistaken?

https://github.com/withastro/docs/blob/d730c492e879e6633fb6d3d886cfe3a3a999b847/src/content/docs/ar/basics/astro-pages.mdx?plain=1#L15-L19

Just tried with `.astro` in the content instead of `astro.` and then the `dir="auto"` still works correctly. Would you up for PR’ing a fix to that file? Or are there other places this is happening?
