### ISSUE TITLE
Document `?url` usage in Imports docs

### ISSUE THREAD

**Issue by tomasklaen** [withastro/docs#8417]
### 📋 Explain your issue

The [Imports documentation page](https://docs.astro.build/en/guides/imports/) is missing info on appending `?url` (and other vite import parameters) to import paths to get URLs to arbitrary files for people that need to import anything else that isn't an image.

**Comment by OliverSpeir** [comment]
?raw also might be worth mentioning 

https://v3.vitejs.dev/guide/assets.html

**Comment by sarah11918** [comment]
We do have this information specifically for [CSS imports](https://docs.astro.build/en/guides/styling/#advanced), but I don't see it mentioned for other file imports.

At a minimum, the [CSS imports section of the imports page](https://docs.astro.build/en/guides/imports/#css) could be improved with a link to that "Advanced" section on the CSS page.

And yes, it does seem like having something about the import parameters as they apply to other files would be a good addition here! I think in the "Other Assets" section makes sense? Would be happy to have someone make a PR with an addition using content from the Vite link Oliver dropped! (But not quite as long as that -- closer in length/scope to what we have on the CSS page)

**Comment by sarah11918** [comment]
OK, here's my suggestion for updates to the Imports page:

1. The [CSS imports section of the imports page](https://docs.astro.build/en/guides/imports/#css) gets a `<ReadMore>` component with a link to the advanced styling section:

```
<ReadMore>Read more about advanced CSS import use cases such as a direct URL reference for a CSS file, or importing CSS as a string in the [Styling guide](https://docs.astro.build/en/guides/styling/#advanced)</ReadMore>`
```

2. The [Other Assets section of the imports page](https://docs.astro.build/en/guides/imports/#other-assets) gets a link to Vite:

```
<ReadMore>Read about import use cases appending Vite import paramaters (e.g. `?url`, `?raw`) in [Vite's static asset handling guide](https://v3.vitejs.dev/guide/assets.html)</ReadMore>`
```

Note: you might have to import the `ReadMore` component at the top of the page, since I'm not sure it's used anywhere here!

Would gladly accept a PR with these additions!
