### ISSUE TITLE
There are many ways to create a blog with Astro. How to choose one?

### ISSUE THREAD

**Issue by ttmc** [withastro/docs#8433]
### 📋 Explain your issue

Right now, there are many ways that one could create a blog with Astro. It would be nice if the docs listed the ways, and gave the reader some guidance on how to choose one. (It probably depends on what the reader wants to do. They need guidance.)

As a starting point, how are the following things related?

- There is a "Build a Blog" tutorial in the docs. It builds this: https://github.com/withastro/blog-tutorial-demo
- There is the "Astro Starter Kit: Blog". See https://github.com/withastro/templates/tree/main/templates/blog 
- There are many Astro themes for blogging, both free and paid: https://astro.build/themes/?search=&categories%5B%5D=blog 
- One can use "Content Collections", i.e. https://docs.astro.build/en/guides/content-collections/ 
- There are Astro integrations with external CMSes, see: https://docs.astro.build/en/guides/cms/ 
- There's "Astro DB", "Astro Studio" and "Astro Studio CMS".

**Comment by sarah11918** [comment]
Thank you for this comment! We are in fact restructuring both our introductory page to emphasize the availability of starter templates, and adding a new "Authoring Content" page where taking your feedback into account could work nicely!

You can see a preview of the draft here: https://docs-git-sssidebar-astrodotbuild.vercel.app/en/guides/content/

I will link this PR to the work in progress so I can incorporate it into that page when it's published. In general, Astro attempts to be a base upon which you can do many things. It might be overwhelming to someone to have a huge list in their face of "here are all the ways you can start a blog!" Instead, we document how things work to make the reader aware, and generally leave it up to them because there *is* so much opportunity for taking whatever path you want!

I'll take this into account on the new page, and try to find a balance between overwhelming with options, and empowering with knowledge to make a good choice! :muscle: 

To be linked with #8239
