### ISSUE TITLE
Error in Add last modified time recipe code?

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#8779]
### 📚 Subject area/topic

recipe -- remark plugin last modified time

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/recipes/modified-time/

### 📋 Description of content that is out-of-date or incorrect

From Feedback Fish:

The recipe works on my local dev server, but when i deploy it via github action, for some reason i got 'Invalid date' instead. Im not too sure how to troubleshoot this issue, and it would be great if the docs can cover that as an example as well

**Comment by Fryuni** [comment]
Relying on Git history on CI platforms is a bit problematic. We document this on [Starlight's `lastUpdated` option](https://starlight.astro.build/reference/configuration/#lastupdated) since it is affected by it.

I wrote about the [specific case of Vercel](https://fryuni.dev/notes/vercel-git/), but the same applies to GH actions. The `actions/checkout` action that does the cloning defaults to a [fetch depth of 1](https://github.com/actions/checkout/blob/692973e3d937129bcbf40652eb9f2f61becf3332/adrs/0153-checkout-v2.md#L72-L74).

Maybe something like the Starlight docs would be good here, but I don't think it should have anything specific to any platform. This problem happens to almost all of them, and each has a different way to opt out of that behavior when they even have that option.

**Comment by sarah11918** [comment]
When you say "maybe something like", do you mean adding the text about "this may not be accurate?", or do you mean trying to write the recipe "in the way that Starlight does it"?

**Comment by Fryuni** [comment]
Adding a text in this line:

> Reporting the Git time may not be accurate depending on the environment in which the project is being built. Hosting platforms, CIs, and automated testing platforms commonly don't retrieve the full git history required for Git to return the correct values.

**Comment by sarah11918** [comment]
Gotcha! Would accept a PR to this recipe that adds this after the introduction,  just before the recipe starts, in a note:

``````
:::note[Relying on Git history]
By default, this feature relies on your repository’s Git history and may not be accurate on some deployment platforms performing [shallow clones](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt).
:::
