### ISSUE TITLE
document docs' node version

### ISSUE THREAD

**Issue by olets** [withastro/docs#8856]
### 📚 Subject area/topic

local development

### 📋 Suggested page

[CONTRIBUTING.md](https://github.com/withastro/docs/blob/main/CONTRIBUTING.md)

### 📋 General description or bullet points (if proposing new content)

This repo doesn't name the Node version contributors should use. 

I've found conflicting hints in the [Netlify deploy docs](https://docs.astro.build/en/guides/deploy/netlify/#set-a-nodejs-version) —"Astro requires v18.17.1 or v20.3.0 or higher"— and in the [docs Stackblitz](https://stackblitz.com/~/github.com/withastro/docs) —where `node -v` gives `18.20.3`.

**Comment by sarah11918** [comment]
Hi @olets !

You can find the specified version of Node that docs uses in the [`.nmvrc` file](https://github.com/withastro/docs/blob/main/.nvmrc), but any supported Astro version (stated in the [Installation and Setup prerequisites](https://docs.astro.build/en/install-and-setup/#prerequisites) should work.

Given that any supported value works, I'm not sure where we'd otherwise add this to the documentation, as there's nothing special about contributing to the docs vs. your own Astro project. Did you run into trouble trying to contribute to docs?

**Comment by olets** [comment]
Huh. Not sure why my system didn't pick up on the nvmrc. Maybe I just needed a restart.

False alarm. Thanks
