### ISSUE TITLE
Add SSR pagination example to docs

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#9123]
### 📚 Subject area/topic

Pagination / routing

### 📋 Suggested page

https://docs.astro.build/en/guides/routing/#pagination

### 📋 General description or bullet points (if proposing new content)

Our existing examples all show `getStaticPaths()` for static sites pagination. We should have an SSR example, too!

**Comment by Fryuni** [comment]
I don't think Astro provides any pagination tooling for SSR.

An implementation would depend heavily on where the information is coming from, so it's not something Astro can provide without being super restrictive. We can do it for pre-rendered pages since by their nature you must have all information available at the same time, so we are operating on a simple array that we know contains everything.

**Comment by sarah11918** [comment]
Thanks then, happy to close this one!
