### ISSUE TITLE
Build forms recipe is missing the prerender constant.

### ISSUE THREAD

**Issue by marcitqualab** [withastro/docs#9309]
### 📚 Subject area/topic

Recipe Build Forms

### 📋 Page(s) affected (or suggested, for new content)

https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/build-forms.mdx

### 📋 Description of content that is out-of-date or incorrect

I think that on the step introducing the frontmatter code with `if (Astro.request.method === "POST") {` it is missing the `export const prerender = false;` for hybrid render mode at least. 
Maybe good to add commented line so that the users can uncomment if using hybrid render mode.
This way the docs will more clear and avoid the misleading error of "Content-Type was not one of "multipart/form-data" or "application/x-www-form-urlencoded"."

**Comment by at-the-vr** [comment]
As a comment I think this is a helpful addition although the recipe is suggesting readers to use `output: 'server'` and a quick search for hybrid does provides https://docs.astro.build/en/guides/server-side-rendering/#opting-out-of-pre-rendering-in-hybrid-mode.

**Comment by marcitqualab** [comment]
Hello Atharva, 
Yes I think that the docs with output 'server' should also be updated to 'server' or 'hybrid'. 
And make more explicit options with commented lines and definitions is a good practice that we can often find in linux configuration files. 
More extensive and explicit docs are always more helpful. 
Many thanks :-)

**Comment by sarah11918** [comment]
Hi! I'm just commenting that these docs are being entirely rewritten for 5.0 when we're removing the `hybrid` option entirely, and `static` will actually be hybrid under the hood!

You can see more info here in the huge PR tackling this change: https://github.com/withastro/docs/pull/9339

I know that means that our live docs will be somewhat less explicit in the meantime, as main docs won't update until v5.0 is *stable* (1-3 months from now), but all these changes are being made in the beta 5 docs with the update to how things will work differently!

(And, I will note, I added a TON of `export const prerender = false` to code samples there already, because in v5, that's all you'll need to do! No configuring `hybrid` explicitly, so we'll typically *assume* that's your default use!)

I'm not opposed to someone making **tiny PRs to code samples only** to keep us honest in the meantime and doing something similar to what's in the PR mentioned above with e.g. starting an example with:

```
export const prerender = true // Not needed in 'server' mode
```

That should still be valid even under the new docs. 

Or make comments and updates to things you spot in that PR linked above! You're welcome to contribute there to help us catch everything in the new docs!

But, I'm going to close this issue not because you're wrong and not because it's not important! I totally agree with you! But because we're not focusing on updating current docs at the moment while we have so much updating to do in prep for v5, so this isn't an issue that we're "tracking" per se. These docs are going to change so much, we aren't really thinking of chasing down examples in current docs that won't be relevant soon anyway because hybrid won't even exist, and we'll be phrasing so much differently!

**Comment by marcitqualab** [comment]
All right, many thanks for the explanation.

**Comment by marcitqualab** [comment]
Just a quick update,

IMHO, maintaining the docs with more details and compatibility with the
current version looks like good practice from my point of view.

Most users do not know what is coming, we only see what is there. So making
small updates for the current docs, even if you will rewrite them all
later, I think it will help your user base and adoption.

Many thanks.



Merci, Thanks, Gracias :-)
---------------------------------------------------
Marc Andreu from IT Quality Lab Ltd.
