### ISSUE TITLE
Misleading "HTML-only" in component intro

### ISSUE THREAD

**Issue by thetillhoff** [withastro/docs#9395]
### 📚 Subject area/topic

Components

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/basics/astro-components/

### 📋 Description of content that is out-of-date or incorrect

Right at the start it says (emphasis mine)
> Astro components are the basic building blocks of any Astro project. They are **HTML-only** templating components with no client-side runtime.

A bit further down on the same page, "Component Script" is introduced:
```
---
// Component Script (JavaScript)
---
<!-- Component Template (HTML + JS Expressions) -->
```

So the "HTML-only" is misleading IMO.

**Comment by sarah11918** [comment]
Hi! We use this phrase so that it's clear that your Astro component creates a template that builds to plain HTML. What is special about Astro is that you can use JS expressions in order to build that template, but these expressions are evaluated at build time only, and then the Astro component renders to static HTML. We have found this description helps people avoid the confusion that they should be expecting interactivity or reactivity in their site.
