### ISSUE TITLE
Provide RSS example of rendering MDX document content including components

### ISSUE THREAD

**Issue by djmtype** [withastro/docs#9722]
### 📚 Subject area/topic

RSS or Container API

### 📋 Suggested page

https://docs.astro.build/en/guides/rss/

### 📋 General description or bullet points (if proposing new content)

Provide a simple RSS example of how to render full content including Astro components imported into MDX files. This now seems possible using Astro's Container API. 

I came across this article that provides clear instruction on how to accomplish this. Full credit to the author: 
[https://blog.damato.design/posts/astro-rss-mdx/](https://blog.damato.design/posts/astro-rss-mdx/)

**Comment by sarah11918** [comment]
Thanks for posting this issue so we can track it! Since this relies on the Container API which is still experimental, and subject to even breaking changes, it might be better to add this as a link in our community recipe pages for now! It's more than a "code sample", and really needs several steps to follow, including an experimental API. So we wouldn't normally document this ourselves just yet.

Are you interested in making a PR to the [RSS section of the community recipes](https://docs.astro.build/en/community-resources/content/#rss) to add this as a link? Maybe like:

```md
- [Create a full-content RSS feed using MDX and the Container API](https://blog.damato.design/posts/astro-rss-mdx/)
```

This gives the original author full credit for their post and increases visibility for them while also helping docs readers until we have a stable solution ourselves!

**Comment by djmtype** [comment]
@sarah11918 I made a pull request. Hopefully, that went through.

**Comment by sarah11918** [comment]
Thanks! It looks great! We have also been talking about maybe turning our RSS package into an integration, so I think this PR closes out the issue until any functionality changes and at which point we'd update the docs for it and would absolutely consider that some people may want full content RSS feeds!

**Comment by djmtype** [comment]
@sarah11918 I kinda feel weird about contributing something I didn't write. As mentioned before, full credit to the author, https://blog.damato.design. I don't know if he or she is in Astro discord.
