### ISSUE TITLE
I wish to filter themes that do NOT use Tailwind

### ISSUE THREAD

**Issue by tomByrer** [withastro/docs#9910]
### 📋 Explain your issue

Seems that 90%+ of Astro themes use Tailwind.  I do not want to use Tailwind for various reasons, but I can't find starter themes that do not use it.

Is the theme data somewhere as a JSON or CSV file?

**Comment by delucis** [comment]
We’ve never got round to adding negative filtering to the web UI, mainly because it’s a bit of a tricky UX pattern to design, but you can access the raw data for [all themes](https://portal.astro.build/api/themes) and [themes using Tailwind](https://portal.astro.build/api/themes?technology%5B%5D=tailwind), so should be able to filter the full list based on the second I think, although apologies it’s not the nicest theme exploration experience 😅

**Comment by sarah11918** [comment]
Thanks for jumping in, Chris! I hope there's something here that works for you, Tom!

As this is not really a docs issue for us to fix in the Astro documentation website, I will close this issue, but I hope you find a great template! :raised_hands:

**Comment by tomByrer** [comment]
Thanks @delucis; I looked though this repo for a JSON/MD list of all the submitted themes.
Unfortunately, many, if not most of the repos you linked do use Tailwind.

**Comment by delucis** [comment]
Yeah, that’s possible. These are mostly user-submitted themes and while we ask people to tick those boxes for which tech their themes use, we don’t have the bandwidth to check if they forgot to mention something. I caught a few more in my filter script above by searching for mentions of Tailwind in the body/description, but of course won‘t catch every case.

There aren’t a huge number unfortunately but our official themes are Tailwind-less: https://astro.build/themes/?search=&categories%5B%5D=official
